### ISSUE TITLE
rose bush: suites summary: display summary of task job status

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1012]
`rose bush` summary should display summary task job status, like `cylc gsummary`.

From #918.

**Comment by matthewrmshin** [comment]
I am not convinced that this is necessary, and will result in the web server being hammered. Users should use `cylc gsummary` instead.

**Comment by arjclark** [comment]
@matthewrmshin - based on your last comment shall we close this then?

**Comment by matthewrmshin** [comment]
It is a lot easier to do now that we are storing the task pool. However, I think the functionality is already performed by `cylc gscan`, so I'll close this down as *wontfix* for now.
