### ISSUE TITLE
rose host-select: rank by file system actual free space

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1048]
We can currently configure `rose host-select` to rank by % free space. There is also a requirement to rank by actual free space, which may be more appropriate if the named disks of the hosts in a pool have different sizes.

**Comment by arjclark** [comment]
@matthewrmshin - is there still a requirement for this, or is it disappearing as things move over to clusters like SPICE?

**Comment by matthewrmshin** [comment]
This is a functionality that is very easy to implement, but we don't really have anyone asking for it any more, for various reasons. I'll close this down as *wontfix* for now until requirement is back.
