### ISSUE TITLE
rose bush: cylc-suite.db viewer

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1070]
As we remove information from the cylc logs (mainly just for the default verbosity level), the information in the `cylc-suite.db` database becomes more and more important for debugging.

Rose Bush is essentially a layer on top of the database and other files, so accessing and presenting the database is not a problem.

We should have an interface to the raw database information. This could just be a dump of "select * from task_events;" and "select * from task_states;", or it could take the form of a SQL browser if we were being fancy.

Ben

**Comment by matthewrmshin** [comment]
Given that we have closed down the associated pull request, and that open source SQLite GUIs are readily available, I'll close down this issue as well.
