### ISSUE TITLE
rose edit: check fail-if/warn-if option for individual sections/variables

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1073]
In `rose edit`, variables or sections that have `fail-if` or `warn-if` metadata should have menu options to check that particular condition.

We could also add this kind of checking on a per-page basis via the Page menu. This would also need to be accessible via detached panels.

**Comment by arjclark** [comment]
@dpmatthews - to follow up

**Comment by dpmatthews** [comment]
In general, just re-running the checks for the whole app is probably a better thing to do rather than just checking part of an app.
