### ISSUE TITLE
rose edit: run more built-in checking after macros are run

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1123]
We should probably run some more checking after
macros have been applied, such as format checking
(all namelist items lowercase, etc).

**Comment by arjclark** [comment]
@dpmatthews - to follow up

**Comment by dpmatthews** [comment]
Not really worth it for such an edge case. Any problem would quickly become apparent the next time an app was loaded or checked and the macro would need to be fixed.
