### ISSUE TITLE
Rose Bush "Display Options" indicator and reset.

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1162]
It would be nice to have an indicator to show that result filtering via "Display Options" is active, as it's not obvious if Display Options is collapsed, and a reset button to turn off all active filtering.

(note I have not checked if this has been done since last release, or if it's a duplicate issue).

**Comment by matthewrmshin** [comment]
Relate to #1110.

**Comment by arjclark** [comment]
Closed by #1579
