### ISSUE TITLE
rosie: hangs if subversion requires more than just a password

### ISSUE THREAD

**Issue by RosalynHatcher** [metomi/rose#1204]
Once `rosie` has processed the subversion request for a password, subsequent messages from subversion are not displayed and `rosie` just hangs.

For example; On a system where subversion is not able to store passwords encrypted, after prompting for a password, it then asks the user if it is ok to store the password unencrypted. 
```
-----------------------------------------------------------------------
ATTENTION!  Your password for authentication realm:

   <svn://host:3690> c9249a3e-3897-12e2-a225-7b5bed6b8ed6

can only be stored to disk unencrypted!  You are advised to configure
your system so that Subversion can store passwords encrypted, if
possible.  See the documentation for details.

You can avoid future appearances of this warning by setting the value
of the 'store-plaintext-passwords' option to either 'yes' or 'no' in
'/home/user/.subversion/servers'.
-----------------------------------------------------------------------
Store password unencrypted (yes/no)?
```
This message is not being displayed to the user and `rosie` hangs.

**Comment by matthewrmshin** [comment]
@RosalynHatcher Do you still want us to look at the STDERR problem? (Perhaps we'll just modify our installation instruction to require Subversion 1.8?) Do you still get the infinite loop problem? (If I remember correctly, it was caused by a weird problem with the `kind` attributes of changesets.)

**Comment by RosalynHatcher** [comment]
@matthewrmshin We have now upgraded to Subversion 1.8 and yes it was also in relation to a problem with the kind attributes as far as I recall.  So it is no longer a problem for us, but maybe wise, as you suggest, to require Subversion 1.8.
