### ISSUE TITLE
rose app-upgrade: report broken versions.py

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1234]
The upgrade code has the following try-except:
```python
        try:
            self.version_module = __import__(MACRO_UPGRADE_MODULE)
        except ImportError:
            # No versions.py.
            sys.path.pop()
            self._load_version_macros([])
            return
```

This silently passes if the versions.py file is missing (which is OK) but also
silently passes if the versions.py file fails to import things itself (which
is less OK). We should see if we can give a message to the user in the
second case.

**Comment by matthewrmshin** [comment]
Looks like the issue was fixed by #1356.
