### ISSUE TITLE
rose app-run: improve efficiency of file installation

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1238]
It can take `rose app-run` a long time to install a large number of namelist files. We should have a look to see if we can do anything to optimise the logic.

**Comment by arjclark** [comment]
@matthewrmshin - is this separate from what we saw with the database problem you fixed?

**Comment by matthewrmshin** [comment]
There is a secondary issue here regarding use of temporary location when we have a straightforward 1-source-to-1-target situation.

**Comment by arjclark** [comment]
@matthewrmshin - to test and see if still an issue

**Comment by matthewrmshin** [comment]
A quick test to install 100 namelists in 100 files appears to have acceptable performance on a Lustre file system, so I'll close this issue for now.
