### ISSUE TITLE
rose python code: increase pylint score

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#129]
We could do with tidying up some of the code so it strictly conforms to [PEP 8](http://www.python.org/dev/peps/pep-0008/) and [PEP 257](http://www.python.org/dev/peps/pep-0008/)... apart from the two spaces after a full stop docstring convention (there have to be limits...).

**Comment by matthewrmshin** [comment]
Close. Superseded by pycodestyle and Codacy.
