### ISSUE TITLE
rose config-diff: support metadata-annoted diff of configurations

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1293]
We should provide a utility that gives a graphical or command-line diff
between configurations, using their metadata to annotate the lines.

**Comment by matthewrmshin** [comment]
Have we lost momentum on this?

**Comment by benfitzpatrick** [comment]
I've inherited it since his uplift, and this is the next Rose issue I want to work on.

**Comment by arjclark** [comment]
@matthewrmshin @benfitzpatrick - we've been "low priority"-ing this for a while now as we have Craig's interim solution. I'll be at a meeting with Climate next week so let me know if you plan on forging ahead - am sure they'll be glad to hear the good news!
