### ISSUE TITLE
rose suite-hook: Prevent transfer of very large log files

### ISSUE THREAD

**Issue by dpmatthews** [metomi/rose#1300]
Suite tasks can, potentially, produce very large log files (e.g. an application goes into an infinite loop sending data to stdout until CPU time is exceeded or quota is reached). Currently `rose suite-hook` will attempt to transfer any log files back to the suite host regardless of their size. This can cause problems, both because of the amount of time this could take and the potential to fill up the file system or exceed the users quota limit.

We should implement some sort of limit to prevent this (probably making use of the `--max-size` option to rsync).

**Comment by matthewrmshin** [comment]
This is now handled by cylc/cylc#1503.

**Comment by matthewrmshin** [comment]
Given that this is now done by cylc, I'll close this issue for `rose suite-hook` as a wontfix.
