### ISSUE TITLE
rose app-upgrade, rose macro: support file operations and revert on cancel

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1303]
We should support `file/` or other sub-directory operations somehow
within `rose app-upgrade` and `rose macro`, with the ability to
revert any changes if a user cancels the operation at the prompt.

This could be done by making any operations on a copy
of the app files in a temporary directory first.

**Comment by dpmatthews** [comment]
Not something we want to support. See also #1106.
