### ISSUE TITLE
rose bush: improve performance

### ISSUE THREAD

**Issue by arjclark** [metomi/rose#1309]
More of an ongoing issue.

We should look to see if any performance gains can be made post the cylc data model rewrite.

**Comment by matthewrmshin** [comment]
Rose Bush jobs should be a lot faster on the server side with the new cylc runtime database `task_jobs` table in cylc. (#1649)

**Comment by arjclark** [comment]
@matthewrmshin - can we now close this given the improvements seen following move to `task_jobs` table?

**Comment by matthewrmshin** [comment]
Yes.
