### ISSUE TITLE
Re-organise project tree to better reflect installation requirements

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1331]
The project tree should be re-organised to reflect the component functionalities provided by Rose:
- Rose suite control utilities. (Most of these will be moved to cylc?)
- Rose suite runtime task utilities and built-in applications.
- Rose configuration editing utilities.
- Rosie suite discovery web service server.
- Rosie suite discovery clients and Subversion wrappers.

**Comment by matthewrmshin** [comment]
We should probably follow Cylc's example, and aim to do this soon after we have packaged up Rose in the standard way.

**Comment by oliver-sanders** [comment]
Closing as there isn't really enough of Rose left to organise 😁.
