### ISSUE TITLE
rose app-upgrade, rose macro: handle optional configurations?

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1334]
We should see if it is possible to support optional configurations in macros.

**Comment by benfitzpatrick** [comment]
This should include validator macros as well.

**Comment by benfitzpatrick** [comment]
Improved the importance of this

**Comment by benfitzpatrick** [comment]
N.B. this is not just for 'built-in' macros, all custom macros should have some kind of support for this...

**Comment by arjclark** [comment]
I think one of the priorities should be to get CLI validation of configs against metadata up and running with specified optional config combinations e.g.

rose macro -V --opt-conf-key=opt1 opt2

This should cover most developer cases i.e. load in my main config, apply my optional configs in the desired order, validate the "final" config.
