### ISSUE TITLE
fcm-ignored config items?

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1379]
Configurable items that frequently need changing for a new suite run - e.g. initial cycle point - create an unnecessary revision control conflict problem (or spurious changes, at least, if not conflicts).  I imagine this might be quite a significant problem for complex apps with large numbers of config items (unless you think that every change to a model's configuration warrants creating a new version of the stored suite).  As far as I'm aware Rose does not already have a solution for this problem(?), in which case here's a suggestion:
 * create a new metadata label to identify items of this kind
 * the GUI would save changes to these variables to "rose-suite.conf2" (or similar) by default
 * at run time items in the .conf2 file override those in the .conf file
 * .conf2 files persists so that these changes don't continually get reset,
 * but they are ignored by fcm/svn, so these changes don't get committed  
 * users can force changes to these variables to be saved to the full .conf file if necessary (or just edit the proper .conf value manually, of course)
 * more generally users could choose to save any changes to .conf2, to separate temporary changes from ones intended to be committed after testing (```fcm revert``` doesn't help here if you need to do a test run with both kinds of change at once). 

Just an idea...

**Comment by matthewrmshin** [comment]
@hjoliver I am closing this issue for now, but please feel free to re-open if you don't think the various approaches I have highlighted above would work for you.

**Comment by hjoliver** [comment]
@matthewrmshin - the approaches you've highlighted above go some way towards the functionality I was suggesting, but not all the way, and they require a higher level of Rose expertise than most users have.  Also, you never actually commented specifically on my proposal.  What I'm getting at is something akin to the git index (/staging area) - a way to choose which changes made in a ```rose edit``` session should be made permanent and which - being trivial or experimental - should be ignored or discarded (or retained for later consideration in the same edit session).  A bit like using ```fcm revert rose-app.conf``` to discard all changes after a test run, but for individually selected config items. I think this would be useful for separating meaningful changes from spurious or experimental ones that you don't want contaminating the change history of a suite.  What do you think?  Maybe not worth the effort to implement even if it sounds good?

**Comment by matthewrmshin** [comment]
@hjoliver For experimental changes, perhaps the user-ignored syntax is the way forward? (It is supported by `rose config-edit`.) In a Rose configuration file, it looks like:

```cfg
# Comment before is attached to the setting below...
# This is an experimental setting and will be ignored at run time.
!pizza_topping='chocolate'
```

And if you don't want to muddle the version control history, you can store the change on a branch?
