### ISSUE TITLE
Config items ignored by the GUI only?

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1380]
Consider a suite with some archiving tasks that we decide to make optional.  Cutting the tasks out of the suite graph with a Jinja2 switch is sufficient to stop them being used.  If we put the switch in rose-suite.conf then, it makes sense to use metadata triggers to hide/ignore other archiving-related parameters too (e.g. archive location) since they're not needed if the tasks aren't used.  However, this stops rose from setting the associated variables in the suite definition, so references to them under `[runtime]` will fail Jinja2 processing even though the tasks will not be used.

So is there a case for metadata triggers that hide items in the GUI but are not otherwise "ignored" by rose?

I know we can get around this by wrapping all references to affected variables in the suite.rc with the switch, or supplying hard-wired defaults for them in the suite definition, but this does result in a bit of extra work and complexity that would seem to be unnecessary for the sort of scenario just described.

I expect you're going to say that in general it is safer for unused variables to cause a failure if referenced (however, as this example shows it's not necessarily dangerous ... although we probably couldn't decide automatically).

**Comment by arjclark** [comment]
Agreed by team, do it the hard way - don't reference variables you're not using.
