### ISSUE TITLE
rose_prune archive-logs-at is broken by some cycle point formats

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1418]
Cycle points of the format ```CCYY-MM-DD-Thh``` do not match the regular expression defined at  ```REC_CYCLE_TIME``` at ```lib/python/rose/suite_engine_procs/cylc.py:93```, for instance.

**Comment by matthewrmshin** [comment]
@hjoliver How did you get cycle point in the `CCYY-MM-DD-Thh` format from `rose_prune`?

**Comment by hjoliver** [comment]
@matthewrmshin - I think that's a typo above, presumably I meant ```CCYY-MM-DDThh```.  I'm currently away at a conference for 3 days, will check when I get back on Thursday...
