### ISSUE TITLE
rose-stem: Allow specifying of source which isn't a working copy

### ISSUE THREAD

**Issue by steoxley** [metomi/rose#1444]
Directories specified with the --source option must currently be working copies. It would be helpful if this were not the case. The proposal is that if a source location contains a colon then everything after the colon is the name of the repository for which the source has been specified. e.g.:
- rose stem --source=LOCATION:REP --source=LOCATION2:REP2

It would also be useful if the rose-stem directory itself didn't have to be a working copy.

**Comment by matthewrmshin** [comment]
@arjclark to check with UM team.

**Comment by scwhitehouse** [comment]
Closed by #1792
