### ISSUE TITLE
rosie: Gracefully handle authentication failure

### ISSUE THREAD

**Issue by ScottWales** [metomi/rose#1508]
`rosie` commands prompt the user for a password when it tries to connect to password-protected servers. If the user is unable to provide a password (e.g. if they don't have an account on one of the servers) the `rosie` command will suddenly exit.

We use two Rose servers - 'au', our local server; and 'u', the shared Met Office system. Not all users at our site have an account on the 'u' server. If we configure the 'u' server centrally then users without an account are not able to use Rosie at all.

The cause appears to be [RosieWSClientAuthManager._prompt()](https://github.com/metomi/rose/blob/master/lib/python/rosie/ws_client_auth.py#L183) raising a KeyboardInterrupt if a value isn't provided.

Expected behaviour is that `rosie` ignores or prints a warning for servers it cannot authenticate to, and provides search results for the remaining servers.

**Comment by arjclark** [comment]
See also #224
