### ISSUE TITLE
rose stem: missing directory error in 'rose-stem/' sub-directory of a working copy

### ISSUE THREAD

**Issue by ScottWales** [metomi/rose#1510]
I have a svn working copy in `/scratch/users/saw562/r1279_rose-stem-rebase/`. If I try to run `rose stem` from within the 'rose-stem' subdirectory of this working copy then the directory name is parsed incorrectly, giving me the error:

```
[INFO] Source tree /scratch/users/saw562/r1279_-rebase/rose-stem added as branch
[FAIL] 
[FAIL] Suite directory /scratch/users/saw562/r1279_-rebase/rose-stem/rose-stem is not a valid directory
```

**Comment by matthewrmshin** [comment]
(I have edited the issue comment: use the phrase *working copy* instead of *branch*, remove hyperlink to private resources, etc.)
