### ISSUE TITLE
rose edit: better behaviour for environment variables in values metadata

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1512]
At the moment, having some metadata like this:

```
[env=SOMETHING]
values=bar,baz,$SUITE_SOMETHING
```

causes odd widget behaviour when the environment variable
option is selected from the radiobutton or combobox widget (it doesn't switch
back to a raw text widget). We should see how we can improve this.

**Comment by oliver-sanders** [comment]
Update: At present for the above example rose edit will use a text widget if `$SUITE_SOMETHING` is selected, switching back to a radio button if the text is deleted.

Would a better solution be to remove the text widget behaviour all-together and just display a radio widget?

**Comment by arjclark** [comment]
If the metadata's setup to have the user select a value from the pre-specified list then the radio buttons from said list should be maintained regardless of what the actual value is.
