### ISSUE TITLE
rose app-run: built-in application to run multiple commands in a process pool

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1531]
Some requirements:
* Run a set of commands in a process pool.
* A large number of commands may be very similar - may require some looping.
* Capture STDERR and STDOUT, so the output lines for each command can be printed together.
* Failure options - fail immediately or continue as much as possible.
* Incremental mode - only re-run commands that did not complete successfully last time.
* User interface should be within the context of a Rose application configuration, (but not necessarily confined to the `rose-app.conf` file.)

**Comment by arjclark** [comment]
@matthewrmshin - I'd be interested in taking a crack at this one

**Comment by matthewrmshin** [comment]
Some other considerations:
* Where possible, we should avoid inventing a lot of new configuration settings.
* Should the commands share the same working directory?
* Where looping is concerned, I would imagine that most differences will be controlled via the command lines and their environments. Do we need to handle variations to contents of input files?

N.B. Some process pool examples can be found in `rose.runner` and `rosie.ws_client`.

**Comment by matthewrmshin** [comment]
See also #1462.

**Comment by arjclark** [comment]
Closed by #1696
