### ISSUE TITLE
rosie id: extend to suite run directory?

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1534]
Could/should we extend `rosie id` to give meaningful results when invoked within a
running suite context? For example:

```
rosie id ~/cylc-run/mi-aa123
```

would give:

```
mi-aa123/trunk@4567
```

(We'd also need to extend it to have an option to actually output the branch and revision
as well as the id).

**Comment by benfitzpatrick** [comment]
In terms of provenance, I think the `Last Changed Revision` would be best here.

**Comment by matthewrmshin** [comment]
Are we talking about a `grep` of `$1/log/rose-suite-run.version` or something like that? It is problematic because the suite may be installed from an uncommitted version.

**Comment by benfitzpatrick** [comment]
Yes, basically (probably alter that file to have a specific line with that information).

We can use the `dirty` suffix like Git does for uncommitted versions. It is still useful
information, even if there are diffs.
