### ISSUE TITLE
rose suite-run --new: prompt for confirmation

### ISSUE THREAD

**Issue by kaday** [metomi/rose#1536]
`rose suite-run --new` may need a `This deletes the logs and they will not be available via rose bush. Are you sure?` or added/different functionality.

Moving to or to be done in cylc?

cylc issue: https://github.com/cylc/cylc/issues/1030

**Comment by matthewrmshin** [comment]
The reason why it is undesirable to implement this now is that users may have scripts calling `rose suite-run --new`. An interactive prompt may cause them to hang.

**Comment by dpmatthews** [comment]
Currently it's not easy if you want to run a suite from scratch (i.e. clear out existing share & work directories) but want to retain any previous run output for comparison. I wonder if `--new` should be changed to do this and we then introduce a `--clean` which matches the current behaviour.

**Comment by arjclark** [comment]
It makes sense for `--new` to remain run as if a completely new, from scratch, run that (re)creates the various suite runtime locations. Removing specific things, such as share and work directories, is more of a clean type functionality, so I'm not adverse to a `--clean` option that would clear out existing work and share directories.

**Comment by jonnyhtw** [comment]
I would certainly advocate the implementation of an 'are you sure [y/n]' type check to the `--new` flag if possible, having recently accidentally deleted some data!

Cheers

Jonny

**Comment by arjclark** [comment]
See https://github.com/cylc/cylc/issues/1885

**Comment by hjoliver** [comment]
This issue has recently been raised again at NIWA (ping @jonnyhtw).  Evidently users do accidentally delete important data, occasionally, with over-zealous use of `--new`.   I initially argued that `--new` implies "start from scratch" i.e. delete existing files first, and a command option should not be used if you don't know what it means.  *But* on reflection, maybe `--new` is not sufficiently indicative of the effect it has ... `--nuke` would be better 😬 .   Point taken on an interactive prompt hanging scripts up, but perhaps a prompt could be optional user global config, or overridden in scripts with a `--force` option...

**Comment by jonnyhtw** [comment]
Thanks @hjoliver 

FYI this is already implemented in my branch to my Rose fork here...

https://github.com/jonnyhtw/rose/tree/rose_suite-run_confirmation_when_running_with_--new_flag

Cheers

**Comment by jonnyhtw** [comment]
Just another note that `rosie delete [suite ID]` does already ask the user for a prompt. Admittedly this is unlikely to occur in scripting like `rose suite-run` but it does serve as an example of the utility of this type of prompting IMHO.

Cheers

**Comment by arjclark** [comment]
> Just another note that rosie delete [suite ID] does already ask the user for a prompt. Admittedly this is unlikely to occur in scripting like rose suite-run but it does serve as an example of the utility of this type of prompting IMHO.

Yeah... I ended up putting that in as the rosie delete command can be used to delete local copies in the roses directory as well as copies in the repository depending on whether or not you used the `--local-only` option and it was confusing users what they were about to do - thinking they were going to do one thing but missing the option off the end.

While I don't disagree that this could be useful, it'd probably best be revisited when moving rose suite-run functionality into cylc under: cylc/cylc#1885 as that provides the opportunity for an interface revisit rather than changing behaviour of an existing command.

**Comment by jonnyhtw** [comment]
Thanks for this. Sounds like a sensible compromise! Cheers, Jonny.

**Comment by jonnyhtw** [comment]
> While I don't disagree that this could be useful, it'd probably best be revisited when moving rose suite-run functionality into cylc under: cylc/cylc#1885 as that provides the opportunity for an interface revisit rather than changing behaviour of an existing command.

Thanks for this. Sounds like a sensible compromise! 

Cheers

Jonny

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/4000 which separates the "install" and "run" concepts.

**Comment by jonnyhtw** [comment]
Interested to see all the fun new things in Cylc coming soon! Thanks 😊
