### ISSUE TITLE
rose app-run: poll delays should support ISO-8601 durations

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1552]
Running `rose app-run` with the following:

```cfg
[poll]
delays=0,12*PT15M
# ...
```

currently results in a mysterious error like this:

```
[FAIL] 'M'
```

It turns out that we are not yet supporting ISO-8601 duration for poll delays.

**Comment by kaday** [comment]
Should the error also be a mixed synax error?

**Comment by benfitzpatrick** [comment]
Good point
