### ISSUE TITLE
rosie: full text suite search

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1558]
It could be very useful to be able to search for a `meta` flag or suite text
across all Rosie suites. We could use technologies like MongoDB to
quickly prototype this kind of functionality. If successful, we could look at
integrating this into all Rosie search, including migrating database technology.

A simpler alternative is to use e.g. http://trac-hacks.org/wiki/RepoSearchPlugin.

**Comment by benfitzpatrick** [comment]
#93 is related.

**Comment by arjclark** [comment]
No demand.
