### ISSUE TITLE
rose macro: warn or fail if macro adds uppercase namelist options

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1569]
If a macro adds an uppercase namelist option to a config, it is lowercased
silently on save as part of the normal config tidying. It would be good if the
user was made aware of the change via a warning, or if the uppercase was
spotted and the macro failed.

**Comment by kaday** [comment]
Considering if rose edit should not warn but actually error for uppercase namelist options, thoughts @benfitzpatrick .
