### ISSUE TITLE
rose task-run: warn if --path is used and task environment already set

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1608]
If a user has a cylc suite.rc command scripting of `rose task-run --path=foo` but they
have already set e.g. `eval $(rose task-env)` in their environment scripting, the `--path`
option is silently ignored. There should be some warning.

**Comment by YoonjaeKim** [comment]
부재중 알림: 5월 6일까지 이메일을 확인할 수 없습니다. 
급하신 용무가 있으시면, yoonjae.kma@gmail.com 으로 연락주시기 바랍니다.
 
I am out of office and back on 6th May. 
If you have an urgent issue, please contact me through yoonjae.kma@gmail.com
 
Best,
 
Yoonjae

**Comment by matthewrmshin** [comment]
The issue appears to be more complex, as I am unable to repeat it in a simple case.

**Comment by matthewrmshin** [comment]
I'll close this as invalid, as it is not reproducible. #1636 is proof.
