### ISSUE TITLE
rosie: metadata and update rose-suite.info

### ISSUE THREAD

**Issue by kaday** [metomi/rose#1632]
Split off from #1341 

We have decided to have prefix-specific metadata within the special Rosie suites. Each metadata directory will have its parent prefix - e.g. `meto-foobar` for a prefix `meto`. The `project` option in the `rose-suite.info` file will also contain this prefix.

To reference the `meto-foobar` metadata directory, the `rose-suite.info` file would have to have `project=meto-foobar`.

 - [x] - `rosie create` and `rosie copy` checking of project metadata (`rosie create` probably requires a double step if project metadata is found, both will require a looping process for the user to get it right) 
 - [x] - `copy-mode` (`=never`, `=clear`...) new metadata option, to disallow certain project-metadata-specific option values from being copied automatically from one `rose-suite.info` to another (e.g. clear the value).

Additionally, updating `the rose-suite.info` to include 
 - [x] - metadata value-hints
 - [x] - copy of moved to `description`
 - [x] - remove `issue-list` as under utilised
 - [x] - add the ability to try again keeping the changes if the rules are not meet (including for metadata if project provided) 
 - [x] - ability to add any field and for it to be copied over

Follow on: improve rosie go advanced search #1692

**Comment by matthewrmshin** [comment]
All tasks done.
