### ISSUE TITLE
rose edit: use multiline widget if newlines in entry box

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1659]
A `gtk.Entry` can display weird characters in place of new lines - if a variable value has newlines in it (and no other widget-related information is given), `rose edit` should use a multiline text widget for that variable value.

**Comment by benfitzpatrick** [comment]
Just found my old code - will tidy this up myself.

**Comment by benfitzpatrick** [comment]
> In the test example it seems to render a redundant extra (uneditable) line in the gui after the last line entry e.g.
```
doe
a deer
```
seems a bit confusing as I'd expected to be able to do something with that?

I can't figure out a way to do this without the extra vertical padding at the bottom. We can just put in a raw TextView but it looks odd as it has no border. I propose we either close this or add the code change as is from #1668.

**Comment by oliver-sanders** [comment]
The extra space at the bottom of the field (see screen-shot) is undesirable but I don't see it as being too big an issue. I would propose we re-open and merge #1668 unless there is opposition @metomi/core.

![screenshot-01-types - rose config-edit](https://cloud.githubusercontent.com/assets/16705946/20060933/758371ea-a4f5-11e6-9cff-aa286659bad5.png)

**Comment by arjclark** [comment]
From memory, @benfitzpatrick didn't get round to fixing the issue raised in the review where it renders an undeditable final line. If that's fixed then #1668 can be merged, otherwise not ready for merging as the behaviour is unhelpful

**Comment by oliver-sanders** [comment]
On closer inspection it would appear that the multi-line widget doesn't actually scroll, the text field just grows indefinitely. Options:
- Remove the (broken) scroll functionality.
  - Settings with text more than 20 or so lines long could pose an issue (does this ever happen?).
  - This change resolves the white-space issue.
- Attempt to restore the scroll functionality.
  - I can't see how to do this as the widget is itself contained within a scrolled window and therefore can always grow vertically.
  - Will also require a fix for the white-space problem.
