### ISSUE TITLE
rose suite-run --no-install?

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1661]
It's advisable to restart a rose-cylc suite using `rose suite-run --restart` not `cylc restart` even if no changes have been made to the suite source, because `rose suite-run` knows how to invoke the right version of cylc (cylc doesn't re-invoke itself at a different version yet: https://github.com/cylc/cylc/issues/1522).  But `svn` doesn't have an easy `git stash` equivalent (? at least not that I'm aware of) - what if the suite working copy contains changes that you don't want in the live suite yet?   Would a `--no-install` option be useful?

**Comment by matthewrmshin** [comment]
This is already dealt with by the new command `rose suite-restart` (#1541, rose-2015.03.0).

**Comment by hjoliver** [comment]
(Ah, thanks, we missed that!)
