### ISSUE TITLE
rose suite-run: load cylc gsummary instead of cylc gui

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1676]
`rose suite-run` should load `cylc gsummary` (if it is not already started) by default instead of `cylc gui`. This allows users to run larger number of suites without flooding their desktops with lots of GUIs.

**Comment by benfitzpatrick** [comment]
I don't think it should. Having cylc gui pop up is very usually a good thing in my opinion. I know sometimes it isn't, but I think that's rarer.

For users that have problems with many cylc gui windows, having many cylc gsummary windows would not be an improvement.

**Comment by matthewrmshin** [comment]
> For users that have problems with many cylc gui windows, having many cylc gsummary windows would not be an improvement.

You missed the *(if it is not already started)* bit.

**Comment by benfitzpatrick** [comment]
I did... but I still like `cylc gui` over `cylc gsummary`

**Comment by benfitzpatrick** [comment]
Maybe a configuration option?

**Comment by kaday** [comment]
I agree with Ben that gscan opening on `rose suite-run` should be a configure option.
If Matt wants we could always consider setting the --no-gcontrol as default option for gcylc?

**Comment by matthewrmshin** [comment]
I am more likely to deprecate the `--no-gcontrol` option in favour of a more flexible option to allow the site/user to choose to launch nothing, `cylc gui`, `cylc gscan`, etc.

**Comment by kaday** [comment]
Matt I think that sounds like a good solution.

**Comment by matthewrmshin** [comment]
No demand.
