### ISSUE TITLE
rose suite-run: output information on execution

### ISSUE THREAD

**Issue by kaday** [metomi/rose#1677]
- [ ] - tidy up and consolidate the output information

 - [ ] - report uncommitted changes if version control available

 - [ ] - make the output information visible in the gui by default

 - [ ] - add a timestamped `starting` or `initialised at` to the log

**Comment by matthewrmshin** [comment]
See also #311 and #1066.

**Comment by matthewrmshin** [comment]
Moved all comments to #1066.
