### ISSUE TITLE
rosie go: crashes when too many local suites

### ISSUE THREAD

**Issue by kaday** [metomi/rose#1679]
`rosie go` reports the following error: 
`Unable to retrieve details for local suites`
and at command line reports:
`[WARN] http://fcm1/rosie/mi/query: {'q': [u'or ( idx eq mi-ah444', u'and branch eq trunk )', u'or (`...
rosie go then crashes.
This occurs when the roses/ directory excessed a number of suites, for example188 suites caused rosie go to crash.

**Comment by arjclark** [comment]
potentially we're hitting some sort of url or string length limit there
