### ISSUE TITLE
rosie suite search wildcard fake-out problem

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1681]
This caught me out for a while on the MOSRS shared suite repository.  I will nominate myself for an "idiot of the month" award, but maybe it does raise an interesting (if small!) issue:

Rosie suite search seems not to support wildcard characters or regular expressions.  However, I'd argue that if you don't know that, it's natural to try, for example, entering `*` in order to see "all suites".   If I do this the search engine  returns a bunch of seemingly unrelated suites, which might suggest to me (see "idiot" above) that the wildcard search worked as intended.  However, as I've just found out, the asterisk is interpreted literally and I was seeing only suites with `access-list=*` in their `rose-suite.info` files. :grimacing: 

Would it be worth adding some small print under the web search entry, and expanding the GUI search tooltip, to explain exactly how the entered terms are used in searching?

**Comment by hjoliver** [comment]
I see SQL wildcards do work (```%```), which is nice, but I think most users are unlikely to realise this without some help info.

**Comment by matthewrmshin** [comment]
> but I think most users are unlikely to realise this without some help info.

That's true. We can do with some extra help text.
