### ISSUE TITLE
rose macro: new type (report)

### ISSUE THREAD

**Issue by r-sharp** [metomi/rose#1687]
At present there are two types of rose macros, `Transform` and `Validate`.
I've been working on 'printing' information from config files in /human readable/ form.

I don't want these macros run when a user tries to `validate_all` but they're not strictly Transform macros either as they don't alter the config.

Would it be possible to have a third type of macro, similar to Validate but not included in validate all such as a `Report` type of similar ?

**Comment by matthewrmshin** [comment]
@arjclark or @oliver-sanders to chase up.

**Comment by arjclark** [comment]
@oliver-sanders is in discussion on this one
