### ISSUE TITLE
rose macro: use optional config name in macro

### ISSUE THREAD

**Issue by r-sharp** [metomi/rose#1688]
When macros are run on apps with optional configs (my experience being from the UM apps) the macro is recursively run on all the 'assembled' configs.

However, the macro doesn't 'know' if it's operating on an optional config or the original config. For the purposes of `Report` configs (see issue #1687) it would be very useful to know if the config is based on a `rose-app.conf` file or an optional config.

My preferred method would be to have a value available that contains the optional config name (or None for the main `rose-app.conf`)

This also butts up to #1650 which deals with prompting on keywords multiple times. If the macro could determine if it were operating on an optional config, then it could 'adjust' the initial response to the keyword option if required. i.e. it would allow the macro to append the optional config name to the file name provided by keyword prompt.

**Comment by benfitzpatrick** [comment]
The `rose macro` machinery needs to know if the macro method supports a optional config name keyword argument - e.g.:
```python
    def transform(self, config, meta_config=None, optional_config_name=None):
```
and then pass the optional config name in if it does support it. The `inspect` module can reveal which keyword arguments a method will allow.
