### ISSUE TITLE
rose suite-shutdown: fail on unexpected arguments

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1689]
`rose suite-shutdown u-ab123` in a `u-ab123` suite directory attempts to run `cylc shutdown u-ab123 --force --host=HOST u-ab123`.

This supplies an extra (bad) argument to cylc shutdown, which is interpreted as a bad cycle point.

Instead, the `rose suite-shutdown` command should have failed due to incorrect usage.

**Comment by matthewrmshin** [comment]
This is the correct and standard behaviour. The usage statement can be modified to make it less confusing.
