### ISSUE TITLE
rose arch to not fail if (some) sources are missing

### ISSUE THREAD

**Issue by malcolmbrooks** [metomi/rose#1707]
At present, rose arch will fail if any sources are not found.

This can be a problem if a file is missing for a valid reason, for instance an observation type is unavailable for a particular cycle.

It would be very helpful if there was a syntax in rose arch to specify that a particular source should not cause rose arch to fail if the source cannot be found. Somthing like:

[arch:$ARCHIVING_PREFIX/${ROSE_TASK_CYCLE_TIME}_${ROSE_TASK_PREFIX}_aircraftsonde_odb2.gz]
source=glu_odb2/aircraftsonde.odb
skip-if-source-missing=True

This should be done on a source by source basis, and default to fail when missing, as there will be some sources that we always want the archving to fail on if they are not available.

**Comment by matthewrmshin** [comment]
@malcolmbrooks See proposed solution under #1708, and let us know if you don't think it will solve this issue.

**Comment by malcolmbrooks** [comment]
Having run with the solution under #1708 for a few days now, the fix does not really work due to the limitation of it still failing if all sources are optional, and not found.

If all sources are specified as being optional, and none of them are found, then the archiving should not treat that as a failure.

Having something like:
skip-if-source-missing=True

in the specification of a the target, is what is needed here.
