### ISSUE TITLE
rose edit crashes in STASH Request panel

### ISSUE THREAD

**Issue by DrRakhi** [metomi/rose#1722]
. Going to STASH Requests panel of UM vn10.1, rose edit crashes: showing following error: 
 RuntimeError: could not create new GType: gl_um_fcst/widget/stash+StashSummaryDataPanelv1 (subclass of rose+config_editor+plugin+um+widget+stash+BaseStashSummaryDataPanelv1)

![stash_rose_ncmrwf](https://cloud.githubusercontent.com/assets/11418531/10448195/ba8e750e-71a8-11e5-9ada-2dcaa5f63290.png)

**Comment by dpmatthews** [comment]
So far we've not been able to reproduce this problem.
I've tried multiple VMs (Centos 6, Ubuntu 1404 & Ubuntu 1504).

**Comment by DrRakhi** [comment]
We're using Linux  x86_64.

**Comment by DrRakhi** [comment]
The issue has been resolved as it was related with python installation problem. Thanks Dave & team..
