### ISSUE TITLE
Hierarchy of SITE within rose stem.

### ISSUE THREAD

**Issue by adammartins** [metomi/rose#1733]
A user of rose-stem noted that setting SITE in rose-suite.conf had no effect.

The problem was investigated on the understanding that the hierarchy order should be:  (higher to lower precedence)
- command line
- rose-suite.conf (in the suite)
- user rose.conf ($HOME/.metomi)
- site rose.conf (set up centrally)

Upon inspection of the code and after various discussions the hierarchy for the rose-stem automatic options (where SITE is defined) was found to actually be:
- command line
- user rose.conf ($HOME/.metomi)
- site rose.conf (set up centrally)
- rose-suite.conf (in the suite)

After discussions with the rose team it was decided to put this ticket on hold and that ideally the following should happen:
- Migrate handling of SITE into rose proper.
- Following which remove the automatic options capability from rose.

**Comment by arjclark** [comment]
@matthewrmshin to follow up with @steoxley

**Comment by matthewrmshin** [comment]
Agreed with @steoxley and @adammartins that this should be closed, until there is further demand.
