### ISSUE TITLE
rose edit: support better namespace titles for duplicate sections

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1734]
At the moment, the namespace page tree (left hand panel) in rose edit can be fairly unhelpful for duplication sections - e.g.:

```
    -> namelist
        -> foo
            -> 1
            -> 2
            -> 3
```

etc.. It is worse for duplicate sections with funkier labelling strategies (e.g. the 8 letter md5 hashes).

We could probably think of a nice way to label these better in the page tree, perhaps via another metadata option (`title-from-options` set in metadata for a section?) that draws information from the options in the duplicate sections.

**Comment by arjclark** [comment]
Closed in absence of any recent complaints
