### ISSUE TITLE
rosie: metadata further development request

### ISSUE THREAD

**Issue by kaday** [metomi/rose#1766]
- Command line `rose-suite.info` to use the `sort-key` provided by the metadata.
- Command line `rose-suite.info` to add the trigger ignored `!!` for suite if it would fail with `[FAIL]         State should be trig-ignored`

**Comment by arjclark** [comment]
@oliver-sanders to understand requirement

**Comment by oliver-sanders** [comment]
Issue to be solved by evaluating the rose-suite.info file as a part of `rose macro` (builds on #1884).
