### ISSUE TITLE
rose edit: summary panel can segfault on sort

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1794]
For a particular app (highly sensitive to the particular contents), sorting on a particular variable in the summary panel which holds a large number of sections can segfault GTK and crash `rose edit`. It fails with:

```
Segmentation fault (core dumped)
```

or

```
*** munmap_chunk(): invalid pointer
```

I have a particular app that can reproduce this every time. I'll try to get to the bottom of this.

**Comment by benfitzpatrick** [comment]
Same happens for right clicking on a UM STASH summary panel row and opening the `View namelist:...` menu item.

**Comment by oliver-sanders** [comment]
Closed by #1918?

**Comment by matthewrmshin** [comment]
@dpmatthews to chase @benfitzpatrick

**Comment by matthewrmshin** [comment]
@oliver-sanders no.

**Comment by dpmatthews** [comment]
Problem can longer be repeated
