### ISSUE TITLE
rose config-edit: app-upgrade: show all possible versions problems

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1812]
A user (via email) has found a couple of (probably related) issues:

1) The "Show all possible versions" button doesn't work properly (or at least how I'd expect), it only shows the most recent possible version, be it major or minor.

2) If you tick the "Show all possible versions" button in an app that's already at the most recent major version, the "Apply" box stays greyed out and the macro can't be run.

This only affects the gui - command-line upgrades are fine.

**Comment by benfitzpatrick** [comment]
1 - it does work, but populates a drop down box that is not obvious. I'll make it more intuitive and rephrase it.
2 - definite bug.
