### ISSUE TITLE
rose.config.ConfigNode: fix __iter__ method

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1821]
The `__iter__` method in `rose.config.ConfigNode` currently does not work - for example:
```python
import rose.config
a = rose.config.ConfigNode()
for item in a:
    print a
```
fails with:
```
TypeError: __iter__() takes exactly 2 arguments (1 given)
```

**Comment by arjclark** [comment]
@benfitzpatrick - is this with a view to having Jon Seddon propose his fix?

**Comment by benfitzpatrick** [comment]
I am not sure whether it should be 'iterate over the keys' rather than `iterate over the items` in `node.value`.

**Comment by arjclark** [comment]
Tricky given what can be buried in the node - nodes within nodes within nodes

**Comment by matthewrmshin** [comment]
The normal behaviour of a dict is iterate over its keys.

**Comment by jonseddon** [comment]
Hi,

I've made the changes in a branch on my clone (https://github.com/jonseddon/rose/tree/config_iterator_fix). 

However, on running `rose test-battery` on my branch, or even on a clone of the master I get the errors below. Are these to be expected, or do you have any suggestions on how I can prevent them?

Thanks,

Jon


`Test Summary Report`
`-------------------`
`t/rose-task-run/26-app-fcm-make-new-mode-with-cont.t           (Wstat: 0 Tests: 2 Failed: 1)`
`  Failed test:  1`
`t/rose-task-run/08-app-fcm-make.t                              (Wstat: 0 Tests: 8 Failed: 1)`
`  Failed test:  8`
`t/rose-task-run/20-app-fcm-make-dest.t                         (Wstat: 0 Tests: 1 Failed: 1)`
`  Failed test:  1`
`t/rose-task-run/22-app-fcm-make-dest-cont-alt.t                (Wstat: 0 Tests: 1 Failed: 1)`
`  Failed test:  1`
`t/rose-task-run/18-app-fcm-make-ctx-name.t                     (Wstat: 0 Tests: 1 Failed: 1)`
`  Failed test:  1`
`Files=251, Tests=3671, 511 wallclock secs ( 1.95 usr  0.53 sys + 1253.84 cusr 348.05 csys =` `1604.37 CPU)`
`Result: FAIL`

The output from running 26-app-fcm-make-new-mode-with-cont.t on its own is:

`1..2`
`cat: cylc-run/rose-test-battery.FHFh33/share/hello.txt: No such file or directory`
`--- -	2016-02-05 11:25:14.215787746 +0000`
`+++ hello.txt	2016-02-05 11:25:13.786654615 +0000`
`@@ -1 +0,0 @@`
`-Hello World!`
`not ok 1 - 26-app-fcm-make-new-mode-with-cont`
`ok 2 - 26-app-fcm-make-new-mode-with-cont`

**Comment by arjclark** [comment]
Try putting: "module load gcc" in your .profile on the hpc and re-running those tests.

**Comment by jonseddon** [comment]
Brilliant! Thanks! That fixed all but one - do you have any suggestions about this one. I'm afraid that there's no error message. I'm struggling to follow the test myself to work out where it's gone wrong I'm afraid.

`[jseddon@eld254 rose.git]$ ./t/rose-task-run/08-app-fcm-make.t `
`1..8`
`ok 1 - 08-app-fcm-make-status`
`ok 2 - 08-app-fcm-make-t1.out`
`ok 3 - 08-app-fcm-make-t2.out`
`ok 4 - 08-app-fcm-make-t3.out`
`ok 5 - 08-app-fcm-make-t4.out`
`ok 6 - 08-app-fcm-make-t5.out.env`
`ok 7 - 08-app-fcm-make-t5.out.cmd`
`not ok 8 - 08-app-fcm-make-t5-part-2.out`

**Comment by matthewrmshin** [comment]
@jonseddon please feel free to raise a pull request with the change of your branch.

**Comment by arjclark** [comment]
I'd make sure your versions on the hpc and local copy are fully in sync but beyond that, if you raise a pull request as @matthewrmshin suggests it might be easier for us to spot what's happened. `08-app-fcm-make-t5-part-2.out` has previously failed for me with out of sync versions of code.

**Comment by jonseddon** [comment]
Thanks, using the correct version on the HPC fixed that test.
