### ISSUE TITLE
rose suite-gcontrol opening two instances of gcylc

### ISSUE THREAD

**Issue by jonnyhtw** [metomi/rose#1831]
Hi there

Whenever I run the '> rose suite-gcontrol' command I am getting two instances of the GCylc window opening up. My colleague @hjoliver has also noticed this behaviour. Is there something that we can do to fix this on our systems here at NIWA?

Many thanks

Jonny Williams

**Comment by hjoliver** [comment]
(I can confirm this, although haven't looked under the hood.  I'm not sure if it's a long-standing issue as I only used `rose suite-gcontrol` for the first time a few days ago).

**Comment by benfitzpatrick** [comment]
Hi Johnny - is the suite running on `localhost` or somewhere else? What versions of rose and cylc are you running with?

**Comment by benfitzpatrick** [comment]
OK, we think that this only happens when the suite is run on a remote host and then the user ssh-es into the remote host and runs `rose suite-gcontrol` there.

Matt's recent pull request (https://github.com/metomi/rose/pull/1824) seems to fix it - can you confirm that?

**Comment by matthewrmshin** [comment]
The only other possibility is that you have configured a group of possible suite hosts, AND `localhost` is one of those hosts, AND for some reason, the logic fails to recognise that one of the configured host names is a host name for the `localhost`, which is very very rare.

(Definitely not a known issue. Otherwise it would have been fixed.)

**Comment by hjoliver** [comment]
> OK, we think that this only happens when the suite is run on a remote host and then the user ssh-es into the remote host and runs rose suite-gcontrol there.

Our setup here is pretty simple - we don't run suites from (or on) our desktop boxes.  We ssh to any one of a number of HPCF linux servers, which all see the same filesystem, run `rose suite-run` there, and the suite always starts up on the same host (i.e. `localhost`).  Similarly, to open gcylc again later, users will ssh to their chosen suite host and run `rose suite-gcontrol` there.   Rose config is just `[rose suite-run]hosts=localhost`. 

Two GUI instances pop up, the text in the title bars looks instructive - one says `foo - localhost:7768`, the other says `foo - wrh-1:7768`  (running suite `foo` on host `wrh-1.hpcf.niwa.co.nz`).

Furthermore, I occasionally get one of the gcylc instances pop up with just "foo" in its title bar (no `host:port`) - these windows stay totally blank (no widgets at all) and have to be killed.  This can happen after `gcylc foo` too, so it must be a cylc issue, not rose.

**Comment by matthewrmshin** [comment]
> Two GUI instances pop up, the text in the title bars looks instructive - one says `foo - localhost:7768`, the other says `foo - wrh-1:7768` (running suite foo on host `wrh-1.hpcf.niwa.co.nz`).

Sounds like the logic fails to recognise that one of the configured host names is a host name for the `localhost`. (It always looks for suites in `localhost` for safety.)

In any case, #1824 should reduce the possibility of this problem - as long as we are using cylc-6.8.0 or above. With our recent port file change, `rose suite-gcontrol [--name=NAME]` has been reduced to become a simple wrapper for `cylc gui NAME` (or `cylc gui "$(basename "$PWD")"`).

**Comment by hjoliver** [comment]
(no time to test this today, pre Singapore trip - it isn't a particularly urgent problem in any case).

**Comment by jonnyhtw** [comment]
Thanks very much for your help on this. It certainly isn't urgent for me either. Please let me know if you need me to do any testing or similar.

Jonny

**Comment by hjoliver** [comment]
Confirmed that this fixes the problem at NIWA - thanks.
