### ISSUE TITLE
rose suite-run --reload after suite `title` change

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1846]
Reported by users at NIWA:  If I change the title of a running suite, `rose suite-run --reload` fails:
```
$ rose suite-run --reload 
[INFO] delete: log/rose-suite-run.conf
...
[INFO] rug: will reload on wrh-1
[FAIL] cylc reload --force rug  # return-code=1, stderr=
[FAIL] security reasons
```
and I get "connection denied" for subsequent client connection attempts.   A `cylc reload` after changing the title in the installed suite definition doesn't have this affect.  I guess `rose suite-run` is nuking the passphrase, but shouldn't be doing so before reloading a running suite (and is it hashing the suite title to make passphrase?)

**Comment by jonnyhtw** [comment]
Hi there

As discussed with Hilary earlier today here at NIWA, I got a similar error when running two branches from the same suite ([this one](https://code.metoffice.gov.uk/trac/roses-u/log/a/b/6/4/2/16x16_niwa_update) & [this one](https://code.metoffice.gov.uk/trac/roses-u/log/a/b/6/4/2/32x16_niwa_update)). These errors necessitated hard killing the runs, deleting the relevant port file and running '> rose suite-run --restart'. I had not renamed them and so this is presumably not exactly the same issue as detailed above but I thought it was worth flagging for completeness. I don't think I did anything else which I don't do routinely. I have attached a screen-grab of the resulting GCylc window when running '> rose suite-gcontrol'

Jonny Williams
 
![grab](https://cloud.githubusercontent.com/assets/12940715/13733722/66846ec0-e9fb-11e5-96a6-7aee50084608.png)

**Comment by hjoliver** [comment]
@jonnyhtw - "ERROR: security reasons; Incorrect suite passphrase?" is not an uncommon error as sooner or later everyone accidentally deletes, moves, or changes a suite passphrase file under a running suite (as discussed, just hard kill your suite and do a restart if this happens).  I'm inclined to think you've done something like that, by accident, as running two branches of a suite at the same time presents no problem to cylc (in fact it's indistinguishable from running two entirely different suites at the same time).  Still, if it happens again and is not due to "user error", please report!

**Comment by matthewrmshin** [comment]
It looks like the behaviour is due to `rose suite-run` (whatever option) always calls `cylc refresh`. On change of a suite title, `cylc refresh` un-registers and registers the suite, which re-creates a new passphrase. I can modify `rose suite-run --reload` to not call `cylc refresh`, but perhaps we should also fix `cylc refresh`?

**Comment by arjclark** [comment]
Saw this problem last week here too. Narrowed down to a Rose issue as Matt outlines above.
