### ISSUE TITLE
rose bush: display *jobs* filtered by state

### ISSUE THREAD

**Issue by arjclark** [metomi/rose#1873]
At present rose bush can only filter by final task state so it can be hard to locate _jobs_ of interest which have, e.g. failed.

https://github.com/metomi/rose/pull/1155 looked to do this but was closed down at the time for various pertinent reasons. With the recent cylc database changes we should now be able to make this change which has been on the TODO list for a while now (although we seem to have lost the associated issue).

**Comment by benfitzpatrick** [comment]
:+1:
