### ISSUE TITLE
rose bunch: enhance output for easier reading for large bunch numbers

### ISSUE THREAD

**Issue by arjclark** [metomi/rose#1876]
In apps with large numbers of bunched tasks, it can be non-trivial to identify how many OK/FAIL/SKIP tasks there are and which ones need investigating.

Things we can investigate doing:
- [X] Counts at end of job.out for numbers of things run and their states
- [ ] Direct rose bush links to bunch.err files for bunch items that have failed

**Comment by oliver-sanders** [comment]
Bullet one closed by #1877

**Comment by arjclark** [comment]
Moving to later for point 2 as its a "nice to have" and best thought about in the context of whatever cylc ends up doing for its rose bush replacement.

**Comment by arjclark** [comment]
Closing as will be a cylc issue at point of migrating rose bush over there and the people that did want this are no longer using rose bunch for their use case.
