### ISSUE TITLE
rose file install: check target of symlink

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1893]
Reported by a user here - configuration that looks like this:

``` ini
[file:myfile]
source=/non/existing/path
mode=symlink
```

will happily produce a broken symlink without any warnings or errors.

**Comment by matthewrmshin** [comment]
I suppose we can have a warning. It is not bug, however. Checking of target costs and so it was deliberately skipped.

**Comment by matthewrmshin** [comment]
To elaborate, consider a set of hosts with a shared filesystem and non shared filesystems. Some files may not exist until you are running a task, so the seemingly non existent symbolic link can actually be legitimate.

**Comment by benfitzpatrick** [comment]
True, although not for app-run.

**Comment by BHFock** [comment]
I like to suggest the introduction of the following three file creation modes to address some of the concerns above:

1) `mode=symlink-check-source` fails if source is missing

2) `mode=symlink-check-source-target` , `mode=symlink-check-target-source` fails if source is missing or target exists
 
3) `mode=symlink-check-target` fail is target exists

**Comment by arjclark** [comment]
I think there's a good case here for being able to throw an error in the app-run case - whether we can make it standard behaviour or if it should be an additional mode for the app is up for debate though I guess.

**Comment by BHFock** [comment]
As a user I would like to see this kind of error checking also in a consistent way happening for other file creation modes like `mkdir`, `copy` or fcm checkout. I don't know what the current error raising situation is for these modes.

**Comment by arjclark** [comment]
> As a user I would like to see this kind of error checking also in a consistent way happening for other file creation modes like mkdir, copy or fcm checkout. I don't know what the current error raising situation is for these modes. 

I believe that for the other modes you are fine as the underlying commands (`mkdir`, `cp`, `fcm co`) will throw an error code if they fail. Symmlinking's a bit different from those in that you can successfully run `ln -s` against a non-existant file and it doesn't throw an error so what's needed is an additional check before/after creating the symmlink to check it's valid/not dead. So, in some way then, the file creation modes are being consistent in their handling of errors. @matthewrmshin / @benfitzpatrick please correct me if I'm remembering this wrong.

**Comment by matthewrmshin** [comment]
@arjclark you are spot on. If it is allowed by the operating system, then it should not be an error. If I remember correctly, in the early days of Rose, the logic did check for the existence of the source, but that was actually causing trouble and was in contradiction to the operating system, so the logic was "fixed" to not do it. You can, of course, add a checksum setting to ensure that you have linked in the correct object. This will then ensure that the source exists.

**Comment by matthewrmshin** [comment]
A optional setting to check for existence of symbolic link's target should be sufficient.
