### ISSUE TITLE
fcm_make tasks: fcm-make.log viewable in rose bush

### ISSUE THREAD

**Issue by arjclark** [metomi/rose#1896]
It would be useful to be able to view the fcm-make logs in rose bush for purposes of diagnosing errors all in one place.

At present the log appears to be going to share(?), so maybe the first stage is to make it so the app produces a copy of that file in its log directory?

**Comment by matthewrmshin** [comment]
The full log is basically a combined version of what is in STDOUT and STDERR in double `-v` mode. It can be quite verbose, and so it should not be part of the job output. If the user needs the log to be in his/her `job.out` and `job.err` (e.g. during code development), all he/she needs to do is to run `fcm make -v -v`. (In the built-in application, add the setting `args=-v -v`.)

Unless there is a stronger requirement for a change, I'll close this issue down as a won't fix
