### ISSUE TITLE
rose suite-run: fresh install of app, bin, etc directories without --new?

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1907]
When files or directories are removed from the source suite directory (e.g. `~/roses/foo-ab123/`) they will not be removed from the installation directory by `rose suite-run` unless a `--new` option is used.

This can cause problems where a user has made a change in the source suite to remove something but is mistakenly still relying on the old resources - this will not be reproducible by another user, and will not be indicated in the `log/rose-suite-run.version`.

Is there a way we can do a clean install without nuking `share`, `state`, `log` etc directories in the cylc run directory? Maybe an `rsync --delete` from each subdirectory in the source suite? By default?

**Comment by arjclark** [comment]
No consensus at this time.

--delete should do it but not sure if its a good idea.

**Comment by dpmatthews** [comment]
Superseded by cylc/cylc-flow#3890.
`cylc reinstall` will ensure that any files removed from the source directory get removed from the installation directory.
