### ISSUE TITLE
rose prune runs ssh interactively

### ISSUE THREAD

**Issue by ScottWales** [metomi/rose#1958]
The Rose Prune app calls `ssh` in interactive mode at https://github.com/metomi/rose/blob/master/lib/python/rose/apps/rose_prune.py#L114. If ssh credentials aren't being stored then the prune app will hang indefinitely waiting for a password.

If the flag `-oBatchMode=true` were to be added to the ssh command then ssh would fail with an error if it didn't have access to credentials, which the prune app could handle appropriately

**Comment by benfitzpatrick** [comment]
Hi Scott, I think `get_cmd` should be replacing `ssh` with the setting in the site/user configuration for `[external]ssh`. There is a `BatchMode` switch in the example in [etc/rose.conf.example](https://github.com/metomi/rose/blob/a2f30e5/etc/rose.conf.example#L57).

Could you check whether you have that configured  - e.g. by running `rose config external ssh` and seeing what comes out?

**Comment by matthewrmshin** [comment]
Note: The hard coded default (i.e. in the absence of configuration) has `-oBatchMode=yes` in the list already.

**Comment by ScottWales** [comment]
Strange - I will investigate further. We have a user who's housekeeping task was hanging without any output (using the nested suite).

**Comment by ScottWales** [comment]
Closing as I've not been able to reproduce. Another possibility is that the user's disk quota was exceeded, I will check that if it happens again.
