### ISSUE TITLE
rose edit allows deleting closing quote of a string containing an environment variable

### ISSUE THREAD

**Issue by MartinDix** [metomi/rose#1966]
Filename paths containing $DATAM are common in UM suites.

rose edit displays strings containing environment variables differently to simple strings, using a different color and also showing the quotes

Unfortunately it's possible to delete the closing quote without rose-edit flagging an error. This gets written to the configuration file and to the namelist where it messes up the namelist read.

E.g. rose-edit allows deleting the closing quote of str1 to create a file like this (metadata declares str1 and str2 with type=character)

```
[file:strings.nml]
source=namelist:strings

[namelist:strings]
str1='${DATAM}/abc
str2='xyz'
```

I tried to follow through the validation logic but got confused. It seems that the validate_variables function in value.py skips the validation if the string contains an environment variable. This is probably the right thing to do if one was trying to set a numeric variable from an environment variable, but not here where the environment variable is only part of the string.

**Comment by MartinDix** [comment]
I tried modifying it to only skip if the variable is not of type character, 
https://github.com/MartinDix/rose/commit/cc173d31ab8f695a645c2d890e7183bf116f6eb1

This now works as I expect, showing an error if I delete a quote.

I tested it on a few suites and it didn't flag anything as an error incorrectly. These included cases where numeric variables were set with environment variables. It's still possible to mess things up by incorrectly adding a quote to one of these but that seems a lot less likely than accidentally deleting a quote when editing a string.

**Comment by matthewrmshin** [comment]
@MartinDix Please feel free to raise a pull request.

**Comment by MartinDix** [comment]
It's a bit trickier than I thought. Metadata for some character variables sets allowable patterns. It's incorrect to check these when an environment variable is used. All that should be done is to check that it's a valid string and not try and check anything related to the value.

It seems there's no way command line way to do the sort of metadata checking that rose edit does. This is actually what I was looking for when I noticed the problem with the rose metadata-check documentation. This makes it harder to set up automated tests for this checking.

**Comment by benfitzpatrick** [comment]
Thanks for reporting it the validation skip was intended because an environment variable can itself contain things like an odd number of single quotes when expanded. I admit your `str1='${DATAM}/abc` example can never be a correct character representation, but we do need to be careful.

`rose macro -V` will do the same checking as `rose edit`.

**Comment by matthewrmshin** [comment]
I have absorbed this issue into #2058.
