### ISSUE TITLE
rose suite-run --name=X from multiple source directories

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#1977]
A user has reported accidentally doing `rose suite-run --reload --name=foo` from the wrong suite source directory, which resulted in his existing suite run directory `foo` being overwritten by the wrong suite. 

Could this be avoided by aborting (unless `--force` is used, or similar) if  `rose suite-run` determines that the target run directory's source location has apparently changed?

**Comment by matthewrmshin** [comment]
This should be relatively easy, although I need to check what `--force` currently does to ensure that overloading it is safe.

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/4000 which links the src and run dirs to prevent this sort of mixup from happening.
