### ISSUE TITLE
Remote PBS

### ISSUE THREAD

**Issue by rwedd** [metomi/rose#1997]
Hi

I am trying to install a rose and cylc instance that utilises remote PBS submission from the suite server to the compute system. I am having trouble getting rose to transfer the config/run scripts to the remote compute system, as it thinks it is running locally due to the local PBS submission. Is there a configuration of rose that works for remote PBS submission?

Cheers

**Comment by matthewrmshin** [comment]
@rwedd Can I suggest that you drop us an email to discuss the specifics of your site requirement? The detail can be found under [Rose: Terms of Use > Rose: Maintenance](http://metomi.github.io/rose/doc/rose-terms-of-use.html#team).

**Comment by rwedd** [comment]
Will do, cheers Matthew
