### ISSUE TITLE
Surprising behaviour from commented lines in rose-app.conf

### ISSUE THREAD

**Issue by MartinDix** [metomi/rose#2016]
When making a quick change to a configuration when debugging I often edit a rose-app.conf file directly rather than with rose edit. Old fortran habits kick in and I might do something like change
```
[namelist:test]
a=1
```
to
```
[namelist:test]
a=2
!a=1
```
In this case the processed rose-app-run.conf file will unexpectedly have 
```
[namelist:test]
!a=1
```
Is this intended behaviour? I got caught by this a while ago and I've just helped a colleague who had the same problem.

**Comment by matthewrmshin** [comment]
@MartinDix This is the correct behaviour.

In a Rose configuration file, the exclamation mark in front of a setting is an *ignore* flag. The setting is read by the parser like a normal setting, and so the second statement will override the first. Settings with an ignore flag will not be used by run time applications, but are recognised by applications such as *rose config-edit*. This is also essential behaviour to allow users to override (ignore) settings via optional configurations and/or the `--define=` CLI options.

A genuine comment line starts with a `#` sign, and if you want the comment to *stick* to a setting, you should place it at the line(s) before the setting. E.g. If you do the following, the comment will stick, and will be a genuine comment at run time:

```cfg
[namelist:test]
# Was a=1, set to 2 because ...
a=2
```
