### ISSUE TITLE
Optional app config files do not allow definition of meta path

### ISSUE THREAD

**Issue by jonnyhtw** [metomi/rose#2026]
Hi there

I am trying to change the default meta path for the fcm_make_ocean app in [NIWA](https://code.metoffice.gov.uk/svn/roses-u/a/h/8/8/2/NIWA) branch of the [u-ah882](https://code.metoffice.gov.uk/svn/roses-u/a/h/8/8/2) suite using an optional app config file.

I want to overwrite the default meta path with one local to NIWA. The default meta path is on line 1 of the following file:

`~/roses/u-ah882/app/fcm_make_ocean/rose-app.conf`

But when I try to override this path using the top line of the following file...,

`~/roses/u-ah882/app/fcm_make_ocean/opt/rose-app-niwa.conf`

...  no change is registered when open the suite with `rose config-edit`.

I have attached a screen grab of the state of the `fcm_make_ocean` app in the `rose edit` window after making this change and it does show up as an option, but is not being picked up by the suite. I have a suite config file containing the `SITE' variable (~/roses/[suite ID]/opt/rose-suite.niwa.conf) but it does not seem to work in this case.

The precise revision needed to reproduce this issue is 27097, i.e.:

`fcm co https://code.metoffice.gov.uk/svn/roses-u/a/h/8/8/2/NIWA@27097`

Please let me know if you have any questions about this issue.

Thanks

Jonny

[roseedit.pdf](https://github.com/metomi/rose/files/647523/roseedit.pdf)

**Comment by matthewrmshin** [comment]
Hi @jonnyhtw This usage of the setting is not correct. We'd normally expect the `meta` setting to be a relative path to a configuration metadata location. In your case, it should look like:

```
meta=nemo-cice-fcm-make/HEAD
```

This should allow suites to be portable, as long as its metadata configuration is installed in the search path for the site.

To modify the search path for your site, you should add the `meta-path` setting to the site/user configuration file. E.g.:

```
meta=/home/jonny/rose-meta:/home/matt/rose-meta
```

**Comment by jonnyhtw** [comment]
Thanks Matt

That does make sense in principle however in this case, the metadata for this task exists in a [development branch](https://code.metoffice.gov.uk/svn/moci/main/branches/dev/timgraham/r209_GO6_fcm_configs).

Presumably one shouldn't put the path to every (in this case, MOCI) development branch that one might need in one's meta path?

Thanks!

Jonny

**Comment by matthewrmshin** [comment]
To specify the search path, you can also use:
* the command line option `--meta-path=PATH`.
* the environment variable `ROSE_META_PATH`.

During development, perhaps you can `export ROSE_META_PATH=/path/to/working/copy` in your current shell. Or even set up an `alias dev-rose-edit='env ROSE_META_PATH=/path/to/working/copy rose config-edit'`.
