### ISSUE TITLE
rose sgc: multiple gcylc windows open per running suite when using --all

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2044]
The command `rose sgc --all` can in error open many gcylc windows per running suite (~10 on our site). This is presumed to be relating to un-contactable hosts.

**Comment by matthewrmshin** [comment]
Can this be repeated on master (with #2045) + cylc 7? Host detection logic in Rose has gone through significant change with move from `~/.cylc/ports/SUITE` to `~/cylc-run/SUITE/.service/contact`.

**Comment by oliver-sanders** [comment]
Bug reproducible only in cylc 6.

**Comment by matthewrmshin** [comment]
I'll consider this issue fixed by #2021 - as the logic that triggers this problem is removed by it.
