### ISSUE TITLE
edit: hash symbols appearing after variable names

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2051]
For example:

rose-suite.conf
```ini
[jinja2:suite.rc]
ok=Foo
# Some Comment
bad=Bar
```

![screenshot-temp5 - rose config-edit](https://cloud.githubusercontent.com/assets/16705946/22892411/5a0b81c0-f20a-11e6-8a59-74c4479a42a1.png)

**Comment by matthewrmshin** [comment]
I thought this is the expected behaviour. Do you find this confusing or something?

**Comment by oliver-sanders** [comment]
If it's intended then so be it.
