### ISSUE TITLE
Question for the number of rose.task_run processes

### ISSUE THREAD

**Issue by liu-jianyu** [metomi/rose#2053]
Hi,

When running suite with rose,   there were up to 7 instance of "python -m rose.tasks_run" concurrently running on job host when an APP was launched.

Saying foo,   7 instance of "python -m rose.task_run --verbose  --path=share/builds/*/*/bin  --app-key=foo -O opt"  were launched and running concurrently on job host while foo was running

A little bit of confusing with the number of rose.task_run processes and wondering how to understand what're they exactly doing or if just some screwing settings in my suite ?

Thanks for your time

Regards

Jerry

**Comment by matthewrmshin** [comment]
Hi @liu-jianyu,

If you have specified file installation in your application configuration, it will use multiple processes to process file installation. On completion of the file installation, the processes should be destroyed.

For simple queries of Rose, please email us. Our email address is documented here:
http://metomi.github.io/rose/doc/rose-terms-of-use.html
