### ISSUE TITLE
rose ana: grepper-report-limit

### ISSUE THREAD

**Issue by steoxley** [metomi/rose#2054]
grepper-report-limit can apparently only be set in the user's `.metomi/rose.conf` file. e.g.:

```cfg
[rose-ana]
grepper-report-limit=20
```

It would be useful if this could also be set via Jinja2 in `rose-stem/rose-suite.conf`. The expectation being that if not set here a particular rose-stem implementation would default this to whatever value it deemed sensible. @stevewardle

**Comment by stevewardle** [comment]
See what you think of the attached PR @steoxley - It allows for a configuration section in the rose-ana apps that can provide access to these type of global/optional settings... If you wanted to control it from the `rose-suite.conf` you could do so via an environment variable that gets picked up by the `rose_ana` apps
