### ISSUE TITLE
using `rosie create` to copy [suite ID]/[branch name]

### ISSUE THREAD

**Issue by jonnyhtw** [metomi/rose#2076]
Hi there

It appears that if I want to copy the contents of a branch of a Rose suite (which _isn't_ the trunk) to a brand new suite ID then `rosie copy` seems to work. For example:

`rosie copy u-ab642/control_nucleation_expt@41468`

This is the behaviour that we want to see but it does not seem to be documented either in the [online docs](http://metomi.github.io/rose/doc/rose-rosie-advice.html) or using `rosie copy --help`.

Also, it appears that if you don't use a revision number...

`rosie copy u-ab642/control_nucleation_expt`

... then the head of the _trunk_ is used, not the head of the branch.

Is this the way that you would recommend that we proceed here?

Thanks a lot

Jonny Williams and colleagues at NIWA, NZ.

**Comment by matthewrmshin** [comment]
OK. We'll improve the docs.

However, I am unable to reproduce the other issue, In my test, it correctly uses the *Last Changed Rev* of the branch.

**Comment by jonnyhtw** [comment]
OK great, thanks for that.

The 'issue' reported above regarding revision numbers is actually fine here too, I just checked. I was getting confused between the _Last Changed Rev_ and the _Revision_ of the suite so all good there.

Thanks

Jonny
