### ISSUE TITLE
how "rose suite-log" infers suite run path

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#2108]
`rose suite-log` infers run directory path from owner of the suite source directory (from `os.stat('.').st_uid`).  Presumably this is so you can run `rose suite-log` from other users' suite source directories.   However, the method fails horribly if your suite directory is owned by someone else - this is unlikely, of course, but I've just seen a case of it resulting from someone with admin rights copying a suite between users.     Maybe there is a a better way, or at least a check that could detect this anomalous situation?

**Comment by hjoliver** [comment]
There might be something similar going on with `rose suite-run` too - in the above situation, it ran the suite OK, did not pop up the Cylc GUI.

**Comment by matthewrmshin** [comment]
@hjoliver Do you have any suggestion for a better way?

The functionality is really a best guess, and I think it almost always works, but we can never be safe from admin carelessness.

However, the command does have a `--user=USERNAME` and a `--name=SUITE` options to force it to do the right thing.

If `rose suite-run` does not pop up the `cylc gui`, you should try running `rose suite-run --debug` to see what it is trying to do and what is failing.

**Comment by hjoliver** [comment]
@matthewrmshin - unfortunately the user's mis-owned suite directory no longer exists, and I can't seem to reproduce the `rose suite-run` problem - the cylc gui does pop up for me.  The `rose suite-log` problem is reproducible though: if a suite source dir is owned by root but located under ~bob, and bob runs `rose suite-log` in the source dir: 
```
$ rose suite-log
[FAIL] foo ~root: suite log not found
``` 

>  Do you have any suggestion for a better way?

In this case the it would be better to use the owner of the process, not the directory, **but** I suppose that would break the other use case - i.e. run `rose suite-log` in another user's suite source dir.  On the other hand, would it be more sensible to to require special options (--user, --name) in the that case, rather than cd to other user's source directory to run the command?

**Comment by oliver-sanders** [comment]
This command has been removed in Rose 2.

* `rose suite-log` was migrated into Cylc 7 as `cylc review`.
* At Cylc 8 the GUI is intended to fill this functionality in time.
