### ISSUE TITLE
Use of real paths causing issues with symlink-based disk failover

### ISSUE THREAD

**Issue by DamianAgius** [metomi/rose#2131]
Hi,  Damian here from the Bureau of Meteorology in Australia.

We use a symlink farm to handle disk failovers on our supercomputer - all access to home and data disks must be through the symlink farm, or tasks will break during failover situations.

Rose (I believe in lib/python/rose/suite_run.py) uses the real path when creating the symlinks back to the suites cylc-run directory, which will cause our Rose/Cylc tasks that try to access the work/share directories  to fail during failover.

I notice that Rose also creates a relative symlink for the share/cycle directory, based on the real path.  This could also create issues.

I am unable to post rose suite-run output demonstrating this here, but can provide via email.

Ideally we would like a per-host option that would disable use of real paths (using the root-dir paths as provided to 'rose suite-run').
Are there other options  to resolve our issue?

I will experiment with modifying suite_run.py to see if I can get the behavior we would like, but I have no idea how Rose options are handled, and have no time to learn at this time.

**Comment by matthewrmshin** [comment]
Hi @DamianAgius If we are not able to get to the bottom of this issue, we'll deal with it when we look at cylc/cylc#1885, which is one of our top priorities for next year. In the mean time, feel free to email our team address with more detail.

**Comment by DamianAgius** [comment]
Hi @matthewrmshin 
Thanks.
I have patched  lib/python/rose/suite_run.py to behave as our site requires, and will (as time permits) learn about Rose option handling so I can create a pull request.
What is the process/policy for deciding on configuration naming?
I would also like to email some more details of the issue - where do I find your team email address?

**Comment by matthewrmshin** [comment]
Our team email can be found by clicking "metomi" at the top left of this page.

**Comment by DamianAgius** [comment]
Thanks.

**Comment by matthewrmshin** [comment]
Hi @DamianAgius I suggest that you raise a pull request with the desired change. We can discuss names of any new configuration settings or command line options on the pull request.

**Comment by sadielbartholomew** [comment]
I am looking to close down Issues that may no longer be relevant. @DamianAgius, please can you let us know whether you managed to find a solution for the problem you raised here, based on the email exchange & any PRs you may have put in, etc.? Thanks.

**Comment by DamianAgius** [comment]
@sadielbartholomew - thanks for following up.
We did work around this issue by patching `suite_run.py` to use the supplied path when creating the root-dir directories (but leaving the real path for the preceding logic)

We also have another patch, based on a branch @hjoliver created mid-flight to support our use of multiple clusters sharing boundary nodes, which should be incorporated into Rose via optional configuration.

I will speak with a colleague about bundling these Rose changes into a PR or two, and will get back to the team ASAP.

**Comment by sadielbartholomew** [comment]
Thanks @DamianAgius. Take your time on adding in any fixes, I simply wanted to ensure this Issue was not deprecated or resolved.

**Comment by oliver-sanders** [comment]
We have made some changes in the upcoming versions of Rose and Cylc (Rose 2 and Cylc 8):

* `rose suite-run` is no more.
* `cylc install` is now used to install workflows.
* The Cylc `[install][symlink dirs]` config is now used to link the run dir (or bits of it) to specified location(s).
* `[install][symlink dirs]`  can be configured at the site or user level but *not* the workflow level.
* (although a CLI override exists if you want to change it on a case by case basis).
* The `symlink dirs` functionality does *not* use `os.path.realpath`.

This page gives a quick overview of the change: [cylc 8.0b2 docs](https://cylc.github.io/cylc-doc/8.0b2/html/7-to-8/major-changes/cylc-install.html)

**Comment by oliver-sanders** [comment]
Adding the question label:

* Is this still a problem?
* Has the `symlink dirs` feature in cylc-flow solved this adequately?
* If so suggest adding a test case to the cylc-flow test battery to ensure this functionality is preserved.

**Comment by DamianAgius** [comment]
Hello UKMO team - we hope you are well, and thank you for not forgetting about us (or at least this issue)

`[install][symlink dirs]`  sounds excellent and should solve our issue , in theory  We will have to test this on our new system, which will be problematic as it is not yet ready (and we are staying with Cylc7 on our current systems).

I will close this issue (as we have had a workaround for some time, and I'm guessing development has stopped on `rose` ) and  we can raise another issue against `cylc-flow` if we find it doesn't quite work as expected.
I'll make Jacinta aware of both the new `[install][symlink dirs]` functionality, and closing this issue.
Thanks!
