### ISSUE TITLE
rose suite-run: pgrep for suite processes?

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#2142]
The above functionality was removed by #2109, but the PR doesn't really explain the reason behind the change.   Now `rose suite-run` just trusts the suite contact file on whether or not a suite is already running.  The error message, however, suggests that actual suite processes were found even if the suite was killed leaving an orphaned contact file:
``` 
% rose suite-run
[FAIL] Suite "foo" has running processes on: blob
[FAIL] Try "cylc stop 'foo'" first?
```
This confuses some users.  Could we either:
 * restore the check for processes on the suite host as recorded in the contact file
 * or at least add a more accurate message, i.e. that the is running *according to the contact file*; therefore stop the suite, or kill its processes, OR remove the orphaned contact file.

**Comment by matthewrmshin** [comment]
Yes, the check was removed to fix an issue that was almost like the opposite of this one - checking of a configured host that was not contactable prevented users from starting up suites.

Note:
* The new logic in cylc/cylc#2455 allows any cylc client to do this check on failure to connect to its suite, and when it is sure that the suite is no longer running, it will remove the contact file and report that the suite has stopped.
* Our next priority is to migrate suite start up host selection logic from `rose suite-run` to cylc to solve cylc/cylc#988.

Therefore, I think the only work here is to change the message slightly.

**Comment by hjoliver** [comment]
Ah, that explains it, thanks.  In that case yes, changing the message will do!
