### ISSUE TITLE
rosie disco client: support GObject equivalent of GnomeKeyring

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#2168]
Example can be found here: https://developer.gnome.org/libsecret/unstable/py-examples.html

Looks like it should be relatively straightforward to program up something for GObject libsecret. :secret:

**Comment by sadielbartholomew** [comment]
I have begun to address this (in branch ``i2168-disco-client-password``) however upon attempting to test with a RHEL7 box I have been unable to proceed as ``sqlalchemy`` is not available on that environment & is required to start the ``rosie disco`` utility & indeed to run the associated tests (as is ``cherrypy`` which is also not found locally but can be imported from SciTools). Therefore I am putting this on hold until ``sqlalchemy`` is installed there.
