### ISSUE TITLE
rose suite hangs up while running - rose-task-run command

### ISSUE THREAD

**Issue by puneet336** [metomi/rose#2188]
Hi , 
I am trying to run a rose (2017.10.0) suite on my CRAY HPC setup using batch mode.
I have noticed that the rose suite gets stuck while launching "rose task-run" command. To debug further,  on setting the ROSE_DEBUG=true at - 
```
cylc__job__inst__script() {
# SCRIPT:
echo "Launching suite ..."
export ROSE_DEBUG=true
rose task-run --verbose
}

```

I can see that the stderr is not printing any output after 'rose-task-run' command.
```
+ PYTHONPATH=/home/apps/SiteSoftwares/precompiled/ROSE/2017.10.0_default/lib/python:/home/apps/SiteSoftwares/gnu/PYTHONPACKAGES/2.7.9/ucs4/gnu/4.8.5/PACKAGE_SUITE/1/lib64/python2.7/site-packages/:/home/apps/SiteSoftwares/gnu/PYTHONPACKAGES/2.7.9/ucs4/gnu/4.8.5/TRAC/1.2.2/lib/python2.7/site-packages/:/home/apps/SiteSoftwares/gnu/PYTHONPACKAGES/2.7.9/ucs4/gnu/4.8.5/GENSHI/0.7/lib64/python2.7/site-packages/:/home/apps/SiteSoftwares/gnu/PYTHONPACKAGES/2.7.9/ucs4/gnu/4.8.5/XXDIFF/4.0.1/lib/python2.7/site-packages/:/opt/cray/llm/21.3.446-6.0.4.0_20.1__gbe30105.ari/lib64/python
+ ROSE_UTIL=task-run
+ export PATH PYTHONPATH ROSE_UTIL
+ exec /home/apps/SiteSoftwares/precompiled/ROSE/2017.10.0_default/bin/rose-task-run --verbose
```

I can see that the rose-task-run script launches python code as - 
exec python -m rose.task_run "$@"

Is there a general comment on this behavior of rose-task-run ?. Is there a way to diagnose this further,
Please let me know if i can provide any further information.

**Comment by matthewrmshin** [comment]
@puneet336 You may want to increase the verbosity further by doing `rose task-run -v -v`. If you have access to the job host, you may try running some `ps` or `pstree` commands to see what `rose task-run` is stuck on. Let us know if you need more help.

**Comment by sadielbartholomew** [comment]
I am looking to close down Issues that may no longer be relevant. @puneet336, please can you let us know whether you are still encountering, or having to find a workaround for, a similar problem to that you raised here? If so, can you try now using newer versions of Rose (e.g. the latest release at my date of comment, ``2019.01.2``) & see if that helps? Thanks.
