### ISSUE TITLE
root-dir in rose.conf not working correctly?

### ISSUE THREAD

**Issue by GlennCreighton** [metomi/rose#2197]
I assume this is just user error and not a bug, but I'm running into an issue getting root-dir to properly work for any HOST_GLOB but *.  E.g. the below creates my root directory in $HOME even when working on hpc9-lsn-02d:

[rose-suite-run]
root-dir=hpc*=/my/custom/path
root-dir{share}=hpc*=/my/custom/path
root-dir{share/cycle}=hpc*=/my/custom/path
root-dir{work}=hpc*=/my/custom/path

If I use =*= then my root directory is properly linked to /my/custom/path.  Any ideas as to what the issue could be?

**Comment by matthewrmshin** [comment]
For the settings to work, both of the following conditions must apply:
* `hpc9-lsn-02d` is *not* the same machine you use to run `rose suite-run`.
* `hpc9-lsn-02d` does not share its file system with the machine you use to run `rose suite-run`.

Is this the case?

**Comment by GlennCreighton** [comment]
Ah.  No, neither is true.  I was trying to leverage this feature to run one of my suites within a different storage pool on the same file system. Is there a way to do this at the suite level?  My goal is to not impact other suites owned by the same user (e.g. I don't want to change my .metomi back and forth).  Thanks for the help!

**Comment by matthewrmshin** [comment]
You can configure this per suite if you put the configuration as a top level setting of your `rose-suite.conf`.

**Comment by GlennCreighton** [comment]
Thank you Matt, that worked.
