### ISSUE TITLE
cylc tutorial: odds and ends

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2211]
Docs:

* [ ] ~Extensions for practical exercises~
* [ ] ~[Parametrisation tutorial - use parameter environment templates](https://github.com/metomi/rose/blame/2018.06.0/sphinx/tutorial/cylc/runtime/configuration-consolidation/parameters.rst#L318)~
* [ ] ~[In-situ broadcast example](https://github.com/metomi/rose/blame/2018.06.0/sphinx/tutorial/cylc/furthertopics/broadcast.rst#L96)~
* [ ] ~[Update clock-triggers to the new xtrigger system once it is stabilised](https://github.com/metomi/rose/blame/2018.06.0/sphinx/tutorial/cylc/furthertopics/clock-triggered-tasks.rst#L9)~
* [ ] ~[Cylc message tutorial](https://github.com/metomi/rose/blame/2018.06.0/sphinx/tutorial/cylc/furthertopics/suicide-triggers.rst#L520)~
* [ ] ~Run (Rose/Cylc) code examples against the Parsec upgrader to prevent deprecated syntax creeping into the docs.~
* [ ] ~Update `cylc run` commands according to https://github.com/cylc/cylc/pull/2759~

Tutorial Suite:

* [ ] Provide some sample data an instructions to use it so the tutorial suite can be run of-line.
* [ ] Rainfall data can wrap in the y dimension.
* [ ] Tidy.

**Comment by sadielbartholomew** [comment]
The Cylc tutorial has now been moved to its rightful home under Cylc, in cylc/cylc-doc#38, so I am transferring this Issue to that repo accordingly.

**Comment by sadielbartholomew** [comment]
OK, I was hoping to be able to use the new-ish 'Transfer issue' feature to do this, but it only seems to allow me to transfer to other repositories under this (``metomi``) organisation, not to another one, i.e. ``cylc``. (Though I'm struggling to find online documentation to confirm this or otherwise.) @oliver-sanders shall we therefore do a lift 'n shift?

**Comment by oliver-sanders** [comment]
Don't migrate this issue as it needs to be split up between:

* Rose (for rose tutorial)
* Cylc-Doc (for cylc tutorial)
* Cylc-Sphinx-Extensions (for technical gubbins).
* Cylc Tutorial Suite (tutorial suite)

The Cylc Tutorial Suite is currently homeless, it will probably become (yet) another repository.

**Comment by sadielbartholomew** [comment]
> Don't migrate this issue as it needs to be split up

Oh fair, I'll leave you to decide what to do.

**Comment by oliver-sanders** [comment]
Breaking this down into the different repositories, for reference:

* https://github.com/metomi/rose/issues/2375
* https://github.com/cylc/cylc-doc/issues/58
* https://github.com/cylc/cylc-doc/issues/59
* https://github.com/cylc/cylc-doc/issues/60
* https://github.com/cylc/cylc-doc/issues/61
* https://github.com/cylc/cylc-doc/issues/62
* https://github.com/cylc/cylc-doc/issues/63

**Comment by oliver-sanders** [comment]
Moving the last of this into cylc-doc: https://github.com/cylc/cylc-doc/issues/218
