### ISSUE TITLE
Sharing files between multiple tasks to source in scripts

### ISSUE THREAD

**Issue by ColemanTom** [metomi/rose#2215]
I'm wanting to share a few files between different apps to be sourced by the scripts, with some common shell functions that they will all be using. It could be all apps want to use them, or only a few. An example tree is below. When I use `rose task-run`, it will copy items from the `file` directory into the work directory, but, it doesn't copy across resolved symbolic links.

I was wondering if
1. There is a better approach I should be using?
2. If not, if rose task-run could be setup to resolve and install symbolic links from the file directory (just use `rsync --copy-links`)?

```text
app
├── shared
│   └── file
│       └── share_functions.sh
├── task1
│   └── file
│       ├── a.sh
│       └── shared -> ../../shared/file
├── task2
│   └── file
│       ├── b.sh
│       └── shared -> ../../shared/file
├── task3
│   └── file
│       └── c.sh
└── task4
    └── file
        └── shared -> ../../shared/file
```

**Comment by matthewrmshin** [comment]
You can use configuration inheritance.

In the `rose.app.conf` of each task, you can tell it to inherit files and settings from the shared application. E.g.:

```cfg
import = shared
```

May need an empty `rose-app.conf` under `shared/` for it to work.

https://metomi.github.io/rose/doc/html/api/configuration/rose-configuration-format.html#import-configuration

Please close this issue if this meets your requirement.

**Comment by ColemanTom** [comment]
Ok, I'll close this now. I can see import being useful for some other things I'm looking at, but I think file is the simplest for what I'm doing in this case. Thanks guys.
