### ISSUE TITLE
`> rose suite-run -n[suite name]` confusion

### ISSUE THREAD

**Issue by jonnyhtw** [metomi/rose#2219]
Hi there

Having just mistyped the following correct code to launch a suite, it drew my attention to something...

`rose suite-run --name=foo`

What I actually typed was...

`rose suite-run -name=foo`

This resulted in a suite called `ame=foo`

Presumably it would be a good idea to only launch if `-n [suite name]|--name=[suite name]` is specified?

Cheers

Jonny

**Comment by matthewrmshin** [comment]
This is a combination of the relic of CLI option parsing and what can be regarded as legitimate suite names. (To be honest, I am in 2 minds whether the `=` character should be a legit character in suite names or not.)

The final outcome will likely belong to cylc/cylc#2281 (which will become possible after cylc/cylc#1874) as we are continuing our journey to move `rose suite-run` functionalities to Cylc cylc/cylc#1885.

**Comment by jonnyhtw** [comment]
OK thanks Matt, that's good to know!

I'll close the issue since it's clearly in hand.

Cheers

Jonny
