### ISSUE TITLE
`rose suite-run` needs to know project name; $PROJECT

### ISSUE THREAD

**Issue by jonnyhtw** [metomi/rose#2238]
Hi there

We have a new HPC system and our Cylc suite output data now goes here...

`/some/base/location/$PROJECT/$USER`

... whereas it used to go here...

`/some/base/location/$USER`.

Some users have multiple projects and hence defining `$PROJECT` in their `~/.profile` (for example) doesn't make a lot of sense. 

A temporary solution would be to define `$PROJECT` in the terminal from which `rose suite-run` is launched but presumably this will preclude using the Rose GUI for launching suites from?

Any advise gratefully received!

Thanks

Jonny

**Comment by hjoliver** [comment]
@jonnyhtw - you can export the variable in a terminal before starting the GUI, and then run the suite from the GUI.  However, this is slightly painful.

**Comment by hjoliver** [comment]
For the Rose team:
```
# rose-suite.conf
[env]
PROJECT=foo
```
This gets exported before starting up cylc, but after symlinking the run directory.

Could the variable export just be done first?

**Comment by jonnyhtw** [comment]
Thanks Matt

**Comment by oliver-sanders** [comment]
Hi Jonny,

We have made some changes in the upcoming versions of Rose and Cylc (Rose 2 and Cylc 8):

* `rose suite-run` is no more.
* `cylc install` is now used to install workflows.
* The Cylc `[install][symlink dirs]` config is now used to link the run dir (or bits of it) to specified location(s).
* `[install][symlink dirs]`  can be configured at the site or user level but *not* the workflow level.
* (although a CLI override exists if you want to change it on a case by case basis).

This page gives a quick overview of the change: [cylc 8.0b2 docs](https://cylc.github.io/cylc-doc/8.0b2/html/7-to-8/major-changes/cylc-install.html)

Closing this issue here as it is now outdated. Feel free to re-raise for Cylc 8 / Rose 2 if the new systems don't solve the problem.

> For Cylc 8 / Rose 2 bugs and feature requests:
>
> * For questions, discussions or if you are unsure feel free to drop in on Discourse.
> * If it relates to Cylc functionality (e.g. `cylc install`) please report to https://github.com/cylc/cylc-flow/
> * If it relates to Cylc / Rose interaction (e.g. `rose-suite.conf`) please report to https://github.com/cylc/cylc-rose/
> * If it relates to Rose functionality (e.g. `rose app-run`) please report it here.

**Comment by jonnyhtw** [comment]
> Hi Jonny,
> 
> We have made some changes in the upcoming versions of Rose and Cylc (Rose 2 and Cylc 8):
> 
> * `rose suite-run` is no more.
> * `cylc install` is now used to install workflows.
> * The Cylc `[install][symlink dirs]` config is now used to link the run dir (or bits of it) to specified location(s).
> * `[install][symlink dirs]`  can be configured at the site or user level but _not_ the workflow level.
> * (although a CLI override exists if you want to change it on a case by case basis).
> 
> This page gives a quick overview of the change: [cylc 8.0b2 docs](https://cylc.github.io/cylc-doc/8.0b2/html/7-to-8/major-changes/cylc-install.html)
> 
> Closing this issue here as it is now outdated (but temporally leaving open #2372 which I think is a duplicate). Feel free to re-raise for Cylc 8 / Rose 2 if the new systems don't solve the problem.
> 
> > For Cylc 8 / Rose 2 bugs and feature requests:
> > 
> > * For questions, discussions or if you are unsure feel free to drop in on Discourse.
> > * If it relates to Cylc functionality (e.g. `cylc install`) please report to https://github.com/cylc/cylc-flow/
> > * If it relates to Cylc / Rose interaction (e.g. `rose-suite.conf`) please report to https://github.com/cylc/cylc-rose/
> > * If it relates to Rose functionality (e.g. `rose app-run`) please report it here.

Hey Oliver, 

Thanks for this; sounds all good to me. Yes, I believe #2372 is related to duplicate functionalty.

All the best,

Jonny
