### ISSUE TITLE
--all flag to rose suite-gcontrol not working

### ISSUE THREAD

**Issue by jonnyhtw** [metomi/rose#2244]
Hi there

I'm not sure if this is a Rose or a NIWA issue but since getting on to our new HPC (Māui) the `--all` flag to `rose suite-gcontrol` isn't working.

`rose suite-gcontrol` is working fine but the `--all` flag isn't producing any output.

Are you able to suggest any way of testing whether or not this is a Rose or a NIWA issue?

@hjoliver is this affecting you on Māui too?

Thanks a lot

Jonny

**Comment by matthewrmshin** [comment]
Hi @jonnyhtw In the upcoming #2239, I am changing the behaviour of `rose suite-gcontrol --all` to launch `cylc gscan`. `rose suite-gcontrol --all` was an implementation before we had `cylc gscan`. These days, I'd recommend that you use `cylc gscan` as the primary tool to monitor multiple suites. If you are happy with this, I'll close this issue down.

**Comment by jonnyhtw** [comment]
Hi @matthewrmshin 

Thanks a lot for that. Understood and happy to close the issue.

Cheers

Jonny
