### ISSUE TITLE
Rosie Go crashing on launch

### ISSUE THREAD

**Issue by mwolffe** [metomi/rose#2260]
Hi,

Currently trying to set up rosie for the first time, and consistently getting the same set of errors whenever I try to run the Rosie Go command. Any recommendations?

[mike@minerva ~]$ rosie go

** (process:17538): WARNING **: 14:17:19.196: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:17538): WARNING **: 14:17:19.196: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:17538): WARNING **: 14:17:19.198: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Gtk-Message: 14:17:19.235: Failed to load module "pk-gtk-module"
Gtk-Message: 14:17:19.235: Failed to load module "canberra-gtk-module"

** (process:17576): WARNING **: 14:17:19.608: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:17576): WARNING **: 14:17:19.608: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:17576): WARNING **: 14:17:19.609: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Gtk-Message: 14:17:19.642: Failed to load module "pk-gtk-module"
Gtk-Message: 14:17:19.642: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/home/mike/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/mike/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mike/.local/rose/lib/python/rosie/browser/main.py", line 1502, in <module>
    main()
  File "/home/mike/.local/rose/lib/python/rosie/browser/main.py", line 1484, in main
    raise exc
rosie.ws_client.RosieWSClientError: hello: {}

**Comment by matthewrmshin** [comment]
Hi @mwolffe Some quick questions:
* What version of Rose are you using?
* Have you configured a set of suitable prefixes for Rosie?
* If so, does the basic `rosie hello` command work? If not, run it as `rosie hello -v -v --debug` and send us the output.

**Comment by mwolffe** [comment]
Hi, Rose is version 2018.06.0 .Rosie hello works perfectly fine, giving the below output:

[mike@minerva ~]$ rosie hello
** (process:13376): WARNING **: 15:20:19.801: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'
** (process:13376): WARNING **: 15:20:19.801: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'
** (process:13376): WARNING **: 15:20:19.802: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Gtk-Message: 15:20:19.852: Failed to load module "pk-gtk-module"
Gtk-Message: 15:20:19.852: Failed to load module "canberra-gtk-module"
hello: {}

However, you're probably right about the prefixes being the route cause. Rosie create is now throwing the below error regardless of the prefix given:

(base) [mike@minerva rose-weather-forecasting-suite]$ rosie create
** (process:9391): WARNING **: 15:41:24.145: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'
** (process:9391): WARNING **: 15:41:24.145: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'
** (process:9391): WARNING **: 15:41:24.146: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Gtk-Message: 15:41:24.191: Failed to load module "pk-gtk-module"
Gtk-Message: 15:41:24.191: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/home/mike/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/mike/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mike/.local/rose/lib/python/rosie/vc.py", line 711, in <module>
    main()
  File "/home/mike/.local/rose/lib/python/rosie/vc.py", line 705, in main
    return globals()[name](argv[1:])
  File "/home/mike/.local/rose/lib/python/rosie/vc.py", line 559, in create
    from_id, opts.prefix, opts.project)
  File "/home/mike/.local/rose/lib/python/rosie/vc.py", line 384, in generate_info_config
    prefix = SuiteId.get_prefix_default()
  File "/home/mike/.local/rose/lib/python/rosie/suite_id.py", line 257, in get_prefix_default
    raise SuiteIdPrefixError()
rosie.suite_id.SuiteIdPrefixError: (default): cannot determine prefix location

**Comment by matthewrmshin** [comment]
Are you missing something like this in your site/user configuration:

```
[rosie-id]
prefixes-ws-default=u
```

**Comment by mwolffe** [comment]
Thanks for your help. I added this in and it now displays the error "unable to retrieve settings for prefix: u" as a popup. What might the next step be from here?

**Comment by matthewrmshin** [comment]
Are you trying to use Rosie to access suites under https://code.metoffice.gov.uk/ or elsewhere?

**Comment by matthewrmshin** [comment]
In which case, you will need these:

```
[rosie-id]
prefix-location.u=https://code.metoffice.gov.uk/svn/roses-u
prefix-web.u=https://code.metoffice.gov.uk/trac/roses-u/intertrac/source:
prefix-ws.u=https://code.metoffice.gov.uk/rosie/u
```

I am going to close down this issue. For further support regarding how to set up Rosie for MOSRS, etc, please do so via email. You can find our detail under [metomi](https://github.com/metomi).
