### ISSUE TITLE
New "rose suite-run" config for "root-dir{log}"?

### ISSUE THREAD

**Issue by hjoliver** [metomi/rose#2287]
To allow symlinking of suite log directories to another location, distinct from the data dirs.

This would (I think) allow secure job log access via `cylc review` until we have authentication built in in cylc-8.  Here's how:

- configure `rose suite-run` to symlink log dirs to (say) `/etc/cylc-logs/$USER/cylc-run/<SUITE>/log`
- configure the web server running `cylc review` to a) not follow symlinks; and b) resolve `/etc/cylc-logs` insead of the normal user home directory

The current situation is insecure if your home filesystem is too small to hold thousands of job logs, because then you have to allow your web server to follow symlinks (to arbitrary locations, in principle) and anyone who can see the `cylc review` service host:port can see anything that the web server can see.

Presumably this would be a pretty easy change to make?

**Comment by matthewrmshin** [comment]
(Need to check whether this is easy or not - because `log` may be created before anything else - to ensure that `rose suite-run` have somewhere permanent to write to.)

**Comment by matthewrmshin** [comment]
Having said that, I think we have actually got something built-in to Cylc Review to ensure that it only serves contents from `~USER/cylc-run/SUITE/log/` and a white list of items under `~USER/cylc-run/SUITE/`.

**Comment by hjoliver** [comment]
> (Need to check whether this is easy ...

Good point.  If it's not easy, we'll live with it till cylc-8.

**Comment by hjoliver** [comment]
> Having said that, I think we have actually got something built-in to Cylc Review ...

Ah, that's good to know, I'll see if that makes our systems people happy.  It might still be a problem  that the web server has to be configured to follow symlinks (our home dirs aren't big enough) and users could manually symlink anything.  But if "job.out" etc. are actually whitelisted, that's a significant mitigation.

**Comment by matthewrmshin** [comment]
So the directory structure is created by 3 different methods:

* suite root: https://github.com/metomi/rose/blob/53a4c136de6b2fd00ead973980e5289da271e3cd/lib/python/rose/suite_run.py#L496
* suite log: https://github.com/metomi/rose/blob/53a4c136de6b2fd00ead973980e5289da271e3cd/lib/python/rose/suite_run.py#L517
* suite share/work: https://github.com/metomi/rose/blob/53a4c136de6b2fd00ead973980e5289da271e3cd/lib/python/rose/suite_run.py#L584

On `rose suite-run` without `--clean`, the current behaviour is to tar-gzip the latest `log.*/` directory, etc. (The rationale is that logs from old runs should still be viewable minus their data files.) Hence the separate logic. It will be some extra logic, but I cannot see why we cannot do what you want quite quickly.

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/3884
