### ISSUE TITLE
suite-run|restart: improve feedback w/ suite name arg

### ISSUE THREAD

**Issue by sadielbartholomew** [metomi/rose#2292]
Given the parallel with ``cylc run`` which accepts a registered suite name as an identifier, it seems likely new(er) users may assume a similar CLI structure for ``rose suite-run`` & attempt to pass a suite name argument to point to a specific configuration files instead of running in the relevant directory.

Currently there is no mechanism to make reasonable attempt to detect this, nor is the command reference ``--help`` clear that arguments *excluding* a suite name are passed through to ``cylc run``. So executing ``rose suite-run <ARBITRARY STRING i.e. suite name> -- <ARGS for cylc run>`` will pass the arbitrary string to be processed as the ICP argument to cylc run:

```bash
...
[FAIL] 2019-02-07T11:57:47Z ERROR - 'NoneType' object has no attribute 'parse'
[FAIL] 	Traceback (most recent call last):
[FAIL] 	  File ".../cylc.git/lib/cylc/scheduler.py", line 259, in start
[FAIL] 	    self.configure()
[FAIL] 	  File ".../cylc.git/lib/cylc/scheduler.py", line 390, in configure
[FAIL] 	    self.load_suiterc()
[FAIL] 	  File ".../cylc.git/lib/cylc/scheduler.py", line 1077, in load_suiterc
[FAIL] 	    self.suite_srv_files_mgr.FILE_BASE_SUITE_RC + '.processed'),
[FAIL] 	  File ".../cylc.git/lib/cylc/config.py", line 353, in __init__
[FAIL] 	    icp = ingest_time(icp, my_now)
[FAIL] 	  File ".../cylc.git/lib/cylc/cycling/iso8601.py", line 670, in ingest_time
[FAIL] 	    my_now = parser.parse(my_now)
[FAIL] 	AttributeError: 'NoneType' object has no attribute 'parse'
[FAIL] 2019-02-07T11:57:47Z ERROR - error caught: cleaning up before exit
[FAIL] 2019-02-07T11:57:47Z INFO - Suite shutting down - ERROR: 'NoneType' object has no attribute 'parse'
...
```

The above applies similarly for ``rose suite-restart``, though since ``cylc restart`` takes no arguments except a suite name, it gives an error which makes the issue more traceable.

```bash
...
[FAIL] cylc-restart: error: Wrong number of arguments (too many)
...
```

However, in either case, the cause of error is not explicit & would frustrate the user. We should:

* ensure the command reference ``--help`` & docs are clearer RE suite name & passed-through arguments;
* tweak the logic as cleverly as practicable to detect a misguided argument i.e. anything not a valid ICP i.e. integer, datetime or valid "relative" ICP syntax.

**Comment by matthewrmshin** [comment]
See https://github.com/cylc/cylc/projects/1 - we are going to illuminate this issue soon.

**Comment by oliver-sanders** [comment]
Closing as the `rose suite-run` command has been replaced by `cylc install`.
