### ISSUE TITLE
Python3 tests dependent on rose-suite-run

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2304]
# To Do list
The following tests are dependent on the use of rose suite-run and/or the work being carried out in #2288.

- [x] rose-ana
- [x] rose-task-env
- [x] rose-task-run
- [x] rose-suite-clean
- [x] rose-suite-restart
- [x] rose-suite-run (presumably test will want removing after the app is moved to cylc?)

# WIP branch
PR #2317

**Comment by wxtim** [comment]
## Rose-task-run tests
- [ ] 06-app-prune-iso.t
- [ ] 07-app-arch.t
- [ ] 09-app-prune-work.t
- [ ] 12-app-prune-integer.t
- [ ] 13-app-arch-cmd-out.t
- [ ] 14-app-prune-remove.t
- [ ] 15-app-prune-extglob.t
- [ ] 16-app-prune-point.t
- [ ] 17-app-prune-glob-as-cycle-fmt.t
- [ ] 24-app-fcm-make-fast.t
- [ ] 25-app-fcm-make-new-mode.t
- [ ] 31-app-bunch.t
- [ ] 32-app-arch-compressed.t
- [ ] 33-app-prune-cycle-format.t
- [ ] 37-app-bunch-rm-old.t
- [ ] 38-app-bunch-counts.t
- [ ] 41-app-bunch-default-command.t

**Comment by sadielbartholomew** [comment]
The list has been amended to remove items relating to the Rosie Disco conversion, so we should change the title of this Issue to reflect this. I will do this now myself, since it should not be controversial.
