### ISSUE TITLE
Move rose-check-software from bin to lib

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2309]
`bin/rose-check-software` is a python script that could sensibly be moved to `metomi/rose` and either:
* Have an application created by listing rose-check-software as an entry point in `setup.py`
or 
* Have a thin bash app in the bin directory.

Either way, it may be useful to add some tests, although this could be a separate ticket.

**Comment by sadielbartholomew** [comment]
I am not sure how the opening comment relates to the title here, @wxtim, is it perhaps the text intended for a different Issue?

**Comment by wxtim** [comment]
> I am not sure how the opening comment relates to the title here, @wxtim, is it perhaps the text intended for a different Issue?

No, I just added something only partially relevant to the ticket. I still think some basic testing for this module might be good, but probably not easy enough to be worthwhile.
