### ISSUE TITLE
Rose popener should return consistent types

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2320]
Had I been starting my Python 3 conversion from scratch I'd have added some code to rose.popener.run thus:
```python
        if isinstance(stderr, bytes):
            stderr = stderr.decode()
        if isinstance(stdout, bytes):
            stdout = stdout.decode()
```
This however breaks decode/encode statements used in multiple other places.

**Comment by matthewrmshin** [comment]
We can probably mimic some of Python 3's API like `os.environ` and `os.environb`?
