### ISSUE TITLE
rose suite-run --reload --name=NAME usage issue

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#2329]
If a user issue the command `rose suite-run --reload --name=NAME`, it will install the content of the current working directory to the running suite named `NAME`. Users may be very surprised if the current working directory does not actually contain a later version of the running suite called `NAME`.

If the install source is under `~/roses/NAME`, the correct usage should be:
```sh
# EITHER
cd ~/roses/NAME && rose suite-run --reload
# OR
rose suite-run --reload -C ~/roses/NAME
```

This is unlikely to be resolved before we move this functionality from Rose to Cylc. However, we should definitely bear this issue in mind when we do the migration.

**Comment by oliver-sanders** [comment]
Superseded by https://github.com/cylc/cylc-flow/issues/3890 which provides a safe mechanism for re-installing workflows (analogous to `rose suite-run --reload`).
