### ISSUE TITLE
python3: mojibake

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2345]
Attempt after #2317 

Allow [mojibake](https://en.wikipedia.org/wiki/Mojibake) to pass through `rose.reporter`.

This has been addressed on 2019.01.x in #2343

Likely a different fix will be required for Python3.

**Comment by oliver-sanders** [comment]
@wxtim your Python3 conversion might close this issue?

**Comment by wxtim** [comment]
I may have fixed this, but I'm not completely sure. Do you have a test case?

**Comment by oliver-sanders** [comment]
I don't have a test case as it requires a bit of infrastructure to set up but you can try injecting [non-utf8 characters](https://stackoverflow.com/questions/1319022/really-good-bad-utf-8-example-test-data#comment10712958_1319022) (i.e. read them from a file) into the logic manually and see it it breaks.
