### ISSUE TITLE
"rose suite-run --host=localhost" not working

### ISSUE THREAD

**Issue by dpmatthews** [metomi/rose#2390]
The "--host" option to rose suite-run seems to work as expected in most cases. However, if you specify "--host=localhost" it gets ignored. The same happens if you specify the name of the localhost.

A workaround is to use "rose suite-run -- --host=locahost".

**Comment by MetRonnie** [comment]
I've done some debugging and found the source of the bug - in this file, in the `run` method:
https://github.com/metomi/rose/blob/019117b7cf130b51970545c4946e2d6d7118df34/lib/python/rose/suite_engine_procs/cylc.py#L527-L537

Specifically, this bit:
https://github.com/metomi/rose/blob/019117b7cf130b51970545c4946e2d6d7118df34/lib/python/rose/suite_engine_procs/cylc.py#L543-L544

`self.host_selector.is_local_host(host)` returns `True` if `host == 'localhost'`, so `--host='localhost'` is not appended to the command, whereas any other host supplied will be appended. Also, if `host` is `None`, it does not set it to `'localhost'`, contrary to the method docstring

**Comment by MetRonnie** [comment]
I guess there are 2 options:
```python
if host is None:
    host = 'localhost'
cmd.append('--host=%s' % host)
```
But then that seems to override the default cylc behaviour which might not be desireable.

The other option is:
```python
if host:
    cmd.append('--host=%s' % host)
```
which would mean the docstring should be changed to reflect the actual behaviour

**Comment by wxtim** [comment]
> I guess there are 2 options:

We don't want to do number 1: we rely on the default behaviour where a workflow server is selected from a site config that we have set up.

**Comment by dpmatthews** [comment]
Option 2 looks fine

**Comment by MetRonnie** [comment]
Who should I request reviews from in the PR?

**Comment by MetRonnie** [comment]
@wxtim Although we said a PR on master probably isn't needed, I have found the same mistake in the master code
https://github.com/metomi/rose/blob/02300e2cace6d139714c1b29be2a76ef11526dec/metomi/rose/suite_engine_procs/cylc.py#L532-L533

**Comment by dpmatthews** [comment]
Don't worry about master - we expect to remove this command entirely with Cylc 8.

**Comment by MetRonnie** [comment]
In that case, shall I close this issue?
