### ISSUE TITLE
question about rose check-software 

### ISSUE THREAD

**Issue by aliabdolali** [metomi/rose#2429]
Hi,
I am not sure where to post my question, sorry if here is not the right place.
I am trying to install Rose on NOAA HPC. The first step is check-software showing that some of the packages are not installed on our HPC. We have a conda mirror, but could not find a couple of required packages on it. Our Helpdesk could not find them on the anaconda cloud. 
Here is the list: 
```
- sphinxcontrib.httpdomain
- hieroglyph
- rsvg
- sphinxcontrib.svg2pdfconverter
-fcm

```
I couldn't find them under conda-forge and not on https://anaconda.org/

I found an "fcm" package under the PyPi channel - is that the one I need to use?
I would appreciate if you tell me where I can find the channel. 

```
rose check-software
python2 (2.6.6+, <3) ......................... ok (2.7.5)
cylc ......................................... ok (8.0a2)
py:pygtk (2.12+) ............................. not ok (not found)
py:jinja2 .................................... ok (2.7.2)
Result: FAIL
Rose Bush
---------
py:cherrypy .................................. not ok (not found)
Result: FAIL
Rosie
-----
py:cherrypy .................................. not ok (not found)
py:requests (2.2.1+) ......................... ok (2.6.0)
py:sqlalchemy (0.6.9+) ....................... not ok (not found)
svn (1.8+) ................................... ok (1.11.0)
fcm .......................................... not ok (not found)
perl (5.10.1+) ............................... ok (5.16.3)
Result: FAIL
Documentation Builder
-------------------
python2 (2.7+, <3) ........................... ok (2.7.5)
graphviz-dot ................................. ok (2.30.1)
py:sphinx (1.5.3+) ........................... not ok (not found)
py:sphinx_rtd_theme (0.2.4+) ................. not ok (not found)
py:sphinxcontrib.httpdomain .................. not ok (not found)
py:hieroglyph (1+, <2) ....................... not ok (not found)
Result: FAIL
Documentation Builder - Recommended Extras
------------------------------------------
rsvg ......................................... not ok (not found)
py:sphinxcontrib.svg2pdfconverter ............ not ok (not found)
Result: FAIL
Documentation Builder - PDF Dependencies
----------------------------------------
tex .......................................... ok (3.1415926)
latexmk ...................................... not ok (not found)
pdflatex ..................................... ok (1.40.14)
Result: FAIL
Documentation Builder - Linkcheck Dependencies
----------------------------------------------
py:requests .................................. ok (2.6.0)
Result: PASS
```
Thanks in advance,
AA

**Comment by wxtim** [comment]
Hi Ali,
Thanks for getting in touch - Normally I think that we'd look for a question like this at https://cylc.discourse.group.

Since you are here, however:
Can I clarify which version of Rose you are trying to install? Are you trying to install Rose 2019 (Python 2 based) or Rose 2, which is currently in Alpha, with a lot of its functionality slated to be moved to Cylc?

**Comment by oliver-sanders** [comment]
Hello,

Unfortunately Cylc8 and Rose2 are currently in early alpha, we cannot recommend them for meaningful usage. We aim to release beta versions of both early next year for evaluation purposes. These will be easily installable along with their dependencies via Conda Forge.

In the mean time the Python2 versions Cylc7 and Rose2019 are recommended. They are tarballs that run in-place once added to the `$PATH`, however, you will have to provision their dependencies.

Note that you don't need to install the decencies for building the documentation which include:

- sphinxcontrib.httpdomain
- hieroglyph
- rsvg
- sphinxcontrib.svg2pdfconverter

**Comment by aliabdolali** [comment]
Hi @oliver-sanders and @wxtim 
Thanks for the suggestions. I'll follow up my question in the forum. 
We aim to use Python2 versions Cylc7 and Rose2019 for optimization of WAVEWATCH III code. 

What about fcm? is it https://github.com/metomi/fcm/releases/?

I wonder for the remained dependency we do not have on our hpc, is there a channel that I can access them?
Regards
AA

**Comment by oliver-sanders** [comment]
> What about fcm? is it https://github.com/metomi/fcm/releases/?

Yes, please see the Rose release notes for inter-compatibility between Cylc/Rose/FCM, at the time of writing the current trio is:

* [Cylc 7.9.2](https://github.com/cylc/cylc-flow/releases/tag/7.9.2)
* [Rose 2019.01.4](https://github.com/metomi/rose/releases/tag/2019.01.4)
* [FCM 2019.09.0](https://github.com/metomi/fcm/releases/tag/2019.09.0)

> I wonder for the remained dependency we do not have on our hpc, is there a channel that I can access them?

Which dependencies are you missing? We don't have a Conda release or channel for Cylc7/Rose2019.

The dependencies mentioned above are not required for regular installation (they are only needed by developers to build the documentation when making changes) so can be safely omitted:

- sphinxcontrib.httpdomain
- hieroglyph
- rsvg
- sphinxcontrib.svg2pdfconverter
