### ISSUE TITLE
resurrect rose stem

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2448]
This pair of PRs 
- [cylc/cylc-flow #4116](https://github.com/cylc/cylc-flow/pull/4116) 
- [cylc-rose #45](https://github.com/cylc/cylc-rose/pull/45) 

close [metomi/rose #2448](https://github.com/metomi/rose/issues/2448)

**This is a change which will require a `pip install -e .[all]` to test - there are entry point changes.**

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Appropriate functional tests are included in the [cylc-rose #45](https://github.com/cylc/cylc-rose/pull/45). These are a direct translation of the tests that can be found in the [existing rose-stem test](https://github.com/metomi/rose/blob/master/t/rose-stem/00-run-basic.t).
- [x] No unit tests have been added - this is deliberate - since this is supposed to be a direct translation this would be out of scope.
- [x] No change log entry has been added to Cylc because this feature is only available if the Cylc-Rose plugin is installed.
- [x] Cylc Rose doesn't have a Change log. It probably should.

- [x] I have documented that this feature exists in the cylc-rose ``__init__`` file. Further documentation, or translation of existing Rose-stem docs is required, but IMO out of scope.
- [x] No dependency changes.

**Comment by wxtim** [comment]
I'm going to have a poke....

**Comment by wxtim** [comment]
Changes made by `StemRunner.process` to rose suite-run opts/.
```diff
 ('log_name', None)
-('defines', None)
+('defines', ['[jinja2:suite.rc]SOURCE_SPACESHIP_REV=""', '[jinja2:suite.rc]SOURCE_SPACESHIP_BASE="/net/home/h02/tpilling/rose-tutorial/spaceship_working_copy"', '[jinja2:suite.rc]HOST_SOURCE_SPACESHIP_BASE="vld398:/net/home/h02/tpilling/rose-tutorial/spaceship_working_copy"', '[jinja2:suite.rc]SOURCE_SPACESHIP_MIRROR="fcm:spaceshiptrunk@1"', '[jinja2:suite.rc]SOURCE_SPACESHIP="/net/home/h02/tpilling/rose-tutorial/spaceship_working_copy"', '[jinja2:suite.rc]HOST_SOURCE_SPACESHIP="vld398:/net/home/h02/tpilling/rose-tutorial/spaceship_working_copy"', "[jinja2:suite.rc]RUN_NAMES=['command_spaceship']"])
 ('group', ['command_spaceship'])
 ('no_overwrite_mode', None)
-('source', ['.'])
+('source', ['/net/home/h02/tpilling/rose-tutorial/spaceship_working_copy'])
 ('gcontrol_mode', True)
 ('profile_mode', False)
 ('run_mode', 'run')
@@ -11,13 +11,13 @@
 ('local_install_only_mode', None)
 ('host', None)
 ('debug_mode', None)
-('name', None)
+('name', 'spaceship_working_copy')
 ('remote', None)
 ('install_only_mode', None)
 ('quietness', 0)
 ('verbosity', 1)
 ('strict_mode', True)
-('project', [])
+('project', ['spaceship'])
 ('validate_suite_only_mode', False)
 ('defines_suite', None)
 ('conf_dir', None)

```
