### ISSUE TITLE
tutorial: upgrade for cylc8 and fix the tutorial command

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2454]
Need to sort out the Cylc Tutorial flow first - https://github.com/cylc/cylc-doc/issues/218

* Upgrade to Cylc8/Rose2.
* Package the tutorial files (will need to be moved into `metomi/rose/etc`) see `rose resource`.

**Comment by oliver-sanders** [comment]
No longer blocked :tada:

**Comment by wxtim** [comment]
This can be broken down into:

Edit this list to indicate that you are working on topics.

- [ ] Tutorials
  - [ ] applications.rst
  - [ ] configurations.rst
  - [ ] furthertopics
  - [ ] img, check for Cylc 7 material, delete
  - [ ] index.rst
  - [ ] metadata.rst
  - [ ] rosie.rst
  - [ ] suites.rst
  - [ ] summary.rst
- [ ] Further Topics
  - [ ] command-keys.rst
  - [ ] date-time-manipulation.rst
  - [ ] failif-warnif.rst
  - [ ] img, check for Cylc 7 material, delete
  - [ ] index.rst
  - [ ] macro-development.rst
  - [ ] optional-configurations.rst
  - [ ] polling.rst
  - [ ] rose-arch.rst
  - [ ] rose-bunch.rst
  - [ ] rose-stem-tutorial.rst
  - [ ] rose-stem.rst
  - [ ] trigger.rst
  - [ ] upgrading-macro-development.rst
  - [ ] upgrading.rst
