### ISSUE TITLE
rose prune: remove rysnc of remote logs

### ISSUE THREAD

**Issue by dpmatthews** [metomi/rose#2469]
The rose prune built-in app currently performs an rsync of remote job log files when using the `prune-remote-logs-at=cycle` option.
https://github.com/metomi/rose/blob/2.0b1/sphinx/api/built-in/rose_prune.rst#configuration
We propose removing this functionality.

I think this option dates back to the early days of Cylc when job log retrieval was done by Rose via hook scripts. Performing the log retrieval immediately after task completion sometimes resulted in incomplete log files so the extra rsync prior to pruning remote log files was useful. However, remote log retrieval is now done by Cylc and a configurable delay can be used which should ensure incomplete log files don't occur (or, at least, are very rare). Therefore, the rsync done by rose prune is not necessary and results in additional load on the server running the scheduler (which is where rose prune tasks typically run). Furthermore, Cylc allows you to configure the max size of the job log files to retrieve but this is not used by rose prune which can result in large log files being transferred unexpectedly. Cylc also allows you to not perform remote log retrieval but, again, rose prune will currently perform the rsync regardless.

**Comment by oliver-sanders** [comment]
On hold pending any response from Discourse: https://github.com/cylc/cylc-flow/runs/2792037586?check_suite_focus=true#step:18:899
