### ISSUE TITLE
Investigate why Rosa-rpmbuild isn't working

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2502]
Follow on #2492 

The following should not happen.
```bash
> rosa rpmbuild --help
/net/home/h02/tpilling/metomi/rose/metomi/rose/scripts/rosa-rpmbuild: line 40: rpmdev-setuptree: command not found
```

**Comment by oliver-sanders** [comment]
I think this requires: `yum install rpmdevtools`.

Is it running/failing on CI?

https://command-not-found.com/rpmdev-setuptree

**Comment by dpmatthews** [comment]
I'm not sure whether it makes sense to continue trying to support installing Rose via RPM.
I certainly think it would need a lot of work.
I propose we just remove this command (at least in the short term).

**Comment by wxtim** [comment]
I'll just excise it then.
