### ISSUE TITLE
Rose Date: Remove deprecation warning

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2524]
Rose date is used inside other scripts and the deprecation warning (use isodatetime) that it emits to stderr may break many of these causing customer pain.

Should we:
a) Remove this warning
b) Remove this warning in non-interactive mode?

n.b. Currently we don't have a wrapper script to allow users to access isodatetime in the way they can access Rose and Cylc.

**Comment by wxtim** [comment]
According to @oliver-sanders this is OK because
1 - We intend to deploy an isodatetime wrapper script.
2 - Rose date is putting this warning into stderr, and people using rose date should be using the output of stdout, not err.

@dpmatthews  - If you are satisfied with this answer, please close the issue.

**Comment by dpmatthews** [comment]
Given the widespread us of `rose date` we've decided on option (b) - only warn in interactive mode.
