### ISSUE TITLE
fcm_make: app requires cylc.rose on remote hosts

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2575]
The fcm_make app currently imports `cylc.rose` on remote platforms which means we need cylc-rose installed on remote platforms which is not as intended.

If possible we should remove this dep, quick investigation to find out why it is imported and whether the import is needed in these situations.

**Comment by wxtim** [comment]
I can't see it:

searched for 
- `from cylc`
- `import cylc`
- `cylc.rose`

```bash
> grep -rn cylc\.rose * --include "*.py" --color
metomi/rose/suite_engine_procs/cylc.py:80:        from cylc.rose.platform_utils import get_platforms_from_task_jobs
metomi/rose/suite_engine_procs/cylc.py:110:        from cylc.rose.platform_utils import get_platform_from_task_def
metomi/rose/tests/suite_engine_procs/test_cylc.py:24:    import cylc.rose.platform_utils
metomi/rose/tests/suite_engine_procs/test_cylc.py:26:    pytestmark = pytest.mark.skip(reason="cylc-rose not found")
metomi/rose/tests/suite_engine_procs/test_cylc.py:54:        cylc.rose.platform_utils,
metomi/rose/tests/suite_engine_procs/test_cylc.py:135:        cylc.rose.platform_utils,
```

The only place it's imported in the non-test parts of the code-base are in `get_suite_jobs_auths` (used by rose-prune) and `get_task_auth` which is used by fcm make, but only in the method `_run_orig`, which I hope isn't being called on the remote machine. (Is it possible that this is where the error is?).

Where it's used in the tests it's got logic for handling it's unavailability.
