### ISSUE TITLE
rose date: elegantly deprecate \d+[wdhms] format

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2577]
Rose 2019 supported a deprecated offset format:

https://github.com/metomi/rose/blob/8d1f144b3724734ccad1a347a8b0cf106393f3c1/lib/python/rose/date.py#L206-L214

E.G:

```console
$ rose date now --offset 1h
```

This was listed in the CLI help as deprecated, however, no deprecation warning was produced at runtime.

This back support was dropped at Rose 2, however, is still in use. Due to the prevalent use of `rose date` in bash scripts there is a high likelihood of hard-to-debug errors in Rose 2 resulting from this change.

**Options:**

1) Add a deprecation warning in Rose 2019.
   * Easy enough, users would need to be encouraged to grep through logs for this warning.
2) Continue to support this, but only in `rose date` (and not the newer `isodatetime` command).
   * Less easy as the CLI has not been parsed at this stage so we would need to crudely parse it in Rose.
   * We would also need to apply this fix here https://github.com/metomi/isodatetime/pull/204

Tagging this against 2.0rc3 as a reminder for us to solve this one on that timeframe rather than as a leaning to option (2).

**Comment by oliver-sanders** [comment]
On reflection option (2) might not be *that* hard, here's a rough guestimation:

```python
upgrade_offset(old_string):
    components = {
        unit: num
        for num, unit in self.REC_OFFSET_FIND.findall(offset.lower())
    }
   new_string = 'P'
    for symbol in ['wd']:
        if symbol in components:
            new_string += f'{components[symbol]}{symbol.upper()}'
    has_time = False
    for symbol in ['hms']:
        if symbol in components:
            if not has_time:
                new_string += 'T'
                has_time = True
            new_string += f'{components[symbol]}{symbol.upper()}'
    return new_string

...

# TODO still need to handle the +/- symbols
for ind in len(sys.argv) - 1:
    if sys.argv[ind] in ('--offset', '-s') and REC_OFFSET_FIND.findall(sys.argv[ind + 1].lower()):
        sys.argv[ind + 1] = upgrade_offset(sys.argv[ind + 1])
```

**Comment by dpmatthews** [comment]
This is widely used (unfortunately) so we should support it in Rose if we can
