### ISSUE TITLE
rose date: support for non-iso8601 formats

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2589]
Rose 2019:

```console
$ rose date '2000010101'
2000010101
```

Rose 2:

```console
$ rose date '2000010101'
WARNING: "rose date" is deprecated, use the "isodatetime" command.
Invalid ISO 8601 date representation: 2000010101
```

From the Rose 2 CLI help the following formats should be supported:

    * ctime: `%a %b %d %H:%M:%S %Y`
    * Unix date: `%a %b %d %H:%M:%S %Z %Y`
    * Basic ISO8601: `%Y-%m-%dT%H:%M:%S`, `%Y%m%dT%H%M%S`
    * Cylc: `%Y%m%d%H`

We should back-support the formats where possible / update the documentation where appropriate.

**Comment by wxtim** [comment]
I'm surprised and worried that isn't OK. I would have expected it to be.

**Comment by wxtim** [comment]
@oliver-sanders  I'm mildly concerned that there seems to be support for `%Y%m%d%H` described as "Cylc" - surely the cylc format would include a `T`?

**Comment by oliver-sanders** [comment]
This was the Cylc 5 cycle point format.
