### ISSUE TITLE
Tutorials are out of date

### ISSUE THREAD

**Issue by MetRonnie** [metomi/rose#2607]
Some of the tutorials are not working as they are out of date. E.g. `rose-suite-tutorial`, which relies on a copy of `cylc-forecasting-suite` which is out of date with its cylc-flow counterpart.

Are we going to manually copy over from cylc-flow or try and use some system to keep them up to date?

**Comment by wxtim** [comment]
There is supposed to be some system. I was supposed to implement it and never quite got around to it.

Can we make a GH action update it when it detects a change in Cylc?

**Comment by MetRonnie** [comment]
Not very easy to detect changes in another repo in GH Actions
