### ISSUE TITLE
suggested tools to simplify the use of rose opts

### ISSUE THREAD

**Issue by PhilAndrews** [metomi/rose#2650]
It seems to me that two scripts (or rose commands) would significantly simplify the use and maintenance of rose opt files.

Script 1: would merge an opt file into its rose-app.conf file generating a new rose-app.conf file (which is saved as a new app rather than overwriting the input one). Rose must already do this whenever it uses an opt, but it may not exist as a rose command at the moment.

Script 2: would input two rose-app.conf files and create an opt file from them. This opt file when merged with script 2's first input rose-app.conf file (using script 1) would generate a rose-app.conf file identical to scrpt 2's second input rose-app.conf file. Script 2 is similar to rose config-diff but writes the difference as a valid opts file.

Can existing rose commands already deliver the above functionality? If not, would it be straightforward to provide new commands (or options for existing commands) to provide it?

**Comment by oliver-sanders** [comment]
Hello, yes, the current command line provides both these utilities:

* To merge configurations use `rose config` (e.g. `rose config -f <file1> -f <file2>`).
* To diff configurations use `rose config-diff` (e.g. `rose config-diff <file1> <file2>`).

Docs:

* http://metomi.github.io/rose/doc/html/api/command-reference.html#rose-config
* http://metomi.github.io/rose/doc/html/api/command-reference.html#rose-config-diff

Please note that work will shortly be starting on the replacement for the old `rose edit` GUI. The new tool will support editing optional configs directly.
