### ISSUE TITLE
fileinstall: restore parallism limiting

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2680]
We used to manage file installation processes (e.g. `rsync`s) in a worker pool. We switched to an asyncio implementation, however, the limit was lost in the process:

https://github.com/metomi/rose/pull/2325/files#diff-1a4d9963cf73c867e4dcfdce40251652a0674c8220771f24138b54ef9d4eaf3cL152

We should restore this parallel limit to reduce the risk of issues which could result from it.

**Comment by dpmatthews** [comment]
The lack of any limit can cause failures if you try to do too many rsync's from the same host:
https://serverfault.com/questions/291231/rsync-and-ssh-exchange-identification-connection-closed-by-remote-host

(Here is a good explanation of the MaxStartups setting:
https://stackoverflow.com/questions/31114690/difference-between-maxstartups-and-maxsessions-in-sshd-config)

So, we certainly shouldn't go above 10.
