### ISSUE TITLE
No warning if `--defines` is meaningless

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2691]
If a user were to make a typo and do

```bash
CYLC_VERSION=7 rose suite-run -D 'FOO42'
# or
CYLC_VERSION=8 cylc vip -D 'FOO42'
```

No warning or error is raised despite this define being largely meaningless.

Should we warn when defines are not in the form `[section]key=value` or `key=value`?

**Comment by oliver-sanders** [comment]
What does Rose do in this case? Does it add the entry into the config anyway?

**Comment by wxtim** [comment]
> What does Rose do in this case? Does it add the entry into the config anyway?

It logs it in `log/rose-suite-run.log`. I'm not sure what else you'd expect rose to do with it?

**Comment by oliver-sanders** [comment]
Seems reasonable to error in this situation with `cylc install`.

**Comment by wxtim** [comment]
> Seems reasonable to error in this situation with `cylc install`.

With specific exceptions for `root-dir`?

**Comment by oliver-sanders** [comment]
I don't think `root-dir` has anything to do with this.

**Comment by oliver-sanders** [comment]
```console
$ cylc install -D foo     # ERROR
$ cylc install -D foo=bar # OK
```

This check doesn't need to be schema aware (and can't be because Rose doesn't have a schema to validate against), it only needs to check that the syntax makes vague sense (i.e. contians at least one `=` symbol).

The existing check for root dir should doe what it does at the appropriate time.

**Comment by wxtim** [comment]
Sorry; You're right and I agree with you

**Comment by wxtim** [comment]
Replaced by https://github.com/cylc/cylc-rose/issues/226
