### ISSUE TITLE
Bunch: Not working incrementally on `cylc trigger`

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2698]
### Synopsis

Cylc Triggering a previously run rose bunch task appears to run non-incrementally.

### How to replicate:

```bash
#!/bin/bash
# Complete issue replication:

WORKFLOW="example.rose-bunch"

mkdir -p "${WORKFLOW}/app/bunch"

# Create a workflow:
cat > "${WORKFLOW}/flow.cylc" <<__HERE__
[scheduling]
    initial cycle point = 2069
    [[graph]]
        R1 = bunch

[runtime]
    [[bunch]]
        script = rose task-run

__HERE__

# An empty rose-suite.conf:
touch "${WORKFLOW}/rose-suite.conf"

# This rose-app.conf:
cat > "${WORKFLOW}/app/bunch/rose-app.conf" <<__HERE__
mode=rose_bunch
meta=rose_bunch

[bunch-args]
arg1=true false true

[bunch]
command-format=%(arg1)s
incremental=true
fail-mode=continue

__HERE__

# install and play the workflow
cylc vip ./"${WORKFLOW}" --host=localhost

# Wait for first job to finish
while true; do
    if grep TOTAL "${HOME}/cylc-run/${WORKFLOW}/runN/log/job/20690101T0000Z/bunch/01/job.out"; then
        break
    else
        sleep 5
    fi
done

cylc trigger "${WORKFLOW}//*/*"

# Wait for second attempt to finish
while true; do
    if grep TOTAL "${HOME}/cylc-run/${WORKFLOW}/runN/log/job/20690101T0000Z/bunch/02/job.out"; then
        break
    else
        sleep 5
    fi
done

# This output should show that only one job ran second time around, but in reality all three ran.
cat "${HOME}/cylc-run/${WORKFLOW}/runN/log/job/20690101T0000Z/02/job.out"
```

### Investigation

In https://github.com/metomi/rose/pull/1865 a check for `CYLC_TASK_SUBMIT_NUMBER` was added to prevent new runs picking up old rose_bunch database files and assuming that they could run a rose bunch task in incremental mode.

It was changed to `CYLC_TASK_TRY_NUMBER` at https://github.com/metomi/rose/commit/7757cf02df04bee1152b9b8737cef4f06eac1571, although the reason for this is unclear - @oliver-sanders  can you interpret your own work?

The original reason in #1865 is now irrelevant, because Cylc install should delete the bunch database. *_BUT_* reflows may cause a similar problem, so we probably need to retain this code, and return it to `CYLC_TASK_SUBMIT_NUMBER`

Ideally we should probably run in incremental mode only if this is the first run of this task in a given flow, but at present there is no way of working out whether this is the first time that we have run  task in a given flow, the database does not contain information about the environment of the previous run (apart from the PATH variable).

### Actions:

Pending further discussion on possibly storing flow numbers in the database, we should:
- Put the `CYLC_TASK_SUBMIT_NUMBER` back.
- Turn off incremental mode if flow is not 1?
- Document that in a new flow all bunch tasks will run - this is a fail-safe way of working.

**Comment by oliver-sanders** [comment]
Closed by #2699
