### ISSUE TITLE
rose bunch documentation example typo

### ISSUE THREAD

**Issue by sjrennie** [metomi/rose#2748]
In the rose documentation 2.1.0 for rose bunch
https://metomi.github.io/rose/doc/html/api/built-in/rose_bunch.html#example
there is an example
```
[bunch]
command-format=echo arg1: %(arg1)s, arg2: %(arg2)s, command-instance: %(command-instances)s
command-instances = 4
fail-handle = abort
incremental = True
```
According to my tests, True should be true, capitalized version not accepted.

**Comment by wxtim** [comment]
That looks very much like what the rest of the docs say.

**Comment by wxtim** [comment]
@sjrennie  - please have a look at the change on https://github.com/metomi/rose/pull/2749

**Comment by sjrennie** [comment]
Looks fine to me. Thanks @wxtim
