### ISSUE TITLE
Adding back the usual 'View page source' to the docs ?

### ISSUE THREAD

**Issue by elliotfontaine** [metomi/rose#2802]
Similar to Cylc documentation and most ReadTheDocs projects. Useful when using intersphinx, for checking if a `ref` is present at the location.

`rose/sphinx/conf.py`
```diff
# Don't link RST source page.
- html_show_sourcelink = False
+ html_show_sourcelink = True
```

<img width="1133" alt="Capture d’écran 2024-07-19 à 16 05 37" src="https://github.com/user-attachments/assets/1dc35586-7877-4b5a-8438-bef8f2499816">

**Comment by wxtim** [comment]
I don't see why not. But there may have been a reason, so I'll do some checks.
