### ISSUE TITLE
rose edit: Grouping options in pages

### ISSUE THREAD

**Issue by steoxley** [metomi/rose#394]
Currently the options on a page are displayed alphanumerically by ID. The meta-data option sort-key can be used to change the order manually.

In the current situation it isn't clear how the different options are related to each other. In particular, it would be useful to know simple trigger dependencies before the dependencies were triggered. e.g. that clicking, or removing, a logical switch would deactivate the following several options.

This could potentially be achieved in various ways, e.g. by manually using the sort-key, followed by specifying an "indentation" level (not yet implemented). However, perhaps a better solution would be to use the meta-data to specify that all related options belong to a group unique to that page. The advantages of this approach is that sort-key would be used less, and specifying indentation manually would probably not be required.

Other points:
- Hierarchical grouping within a page would be desirable.
- Using colours or other types of delimitation should be investigated - although indentation is likely to be best for nested groups.

**Comment by arjclark** [comment]
No demand.
