### ISSUE TITLE
rose config-edit: remove wrong-trigger-state variable error

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#406]
Removing a variable with a trigger-state error in the config editor <em>perhaps</em> should remove the error.

**Comment by arjclark** [comment]
Needs an example

**Comment by matthewrmshin** [comment]
In `rose-app.conf`:

```cfg
[namelist:nl1]
foo=1
bar=2
```

In `meta/rose-meta.conf`:

```cfg
[namelist:nl1=foo]
values=1,2
trigger=namelist:nl1=bar: 2;

[namelist:nl1=bar]
```

Launch `rose config-edit`. Remove `bar` from `namelist:nl1` - it will continue to show error.
