### ISSUE TITLE
rose metadata: pattern per element?

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#506]
Should we have the equivalent of <samp>pattern</samp> for individual array elements?

**Comment by matthewrmshin** [comment]
Do we have a use case for this? If not, I suggest that we close this as a *won't fix*.

**Comment by benfitzpatrick** [comment]
For a given array element pattern `X`, you can currently just write:
```
pattern=^(X)(?:,(X))*$
```

so for an array element pattern of `foo|bar`, we can write:

```
pattern=^(foo|bar)(?:,(foo|bar))*$
```

**Comment by benfitzpatrick** [comment]
I'll make this a documentation issue to add the above comment.
