### ISSUE TITLE
rose configuration: support other dump formats for rose app-run

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#585]
Currently, we can only dump information as environment variables or in Fortran namelist format - we could do supporting outputting in some more modern formats that are easy for languages such as Python and Javascript to read. We should definitely support JSON - any others?

**Comment by matthewrmshin** [comment]
Please reopen when there is a real use case.

**Comment by benfitzpatrick** [comment]
Now getting a real use case.

**Comment by matthewrmshin** [comment]
Can we document the use case before reopening the issue? I would like to see the input and output from the user application before we look at this.

**Comment by arjclark** [comment]
@matthewrmshin is working through possible solutions using rose.config with the users in question. If this becomes a common issue we can revisit this, possibly providing an advanced tutorial on working with rose.config
