### ISSUE TITLE
rose documentation: improve syntax highlighting

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#598]
The syntax highlighting used in our documentation is OK, but could be improved.

Examples so far:

```
    [[task_{{ NUM }}]]
```

in a suite.rc cylc example highlights as pure section, but should include Jinja2 highlighting for the `{{ NUM }}` fragment.

**Comment by arjclark** [comment]
@oliver-sanders - investigate how simple this would be to fix

**Comment by oliver-sanders** [comment]
> investigate how simple this would be to fix

Not very.

As far as I can tell google prettify can't handle multiple patterns matching a single section of text and will go with the longest match (and the most recently defined colour?).

**Other Examples:**
```
graph = """
    # some comment
    task_{{num}} => foo {% if var %} => bar {% endif %}
"""
```

**If we are determined to improve syntax highlighting:**
Google prettify no longer appears in the first few pages of google for "javascript syntax highlighter" so is probably on the way out. https://highlightjs.org/ is currently occupying the No1 spot and (unlike prettify) has documentation (including for defining new languages) http://highlightjs.readthedocs.io/en/latest/.

Bumping this back to some-day for now.

**Comment by matthewrmshin** [comment]
@oliver-sanders Can close this one?

**Comment by matthewrmshin** [comment]
Close by #2184.
