### ISSUE TITLE
rose: fork sub-processes

### ISSUE THREAD

**Issue by arjclark** [metomi/rose#655]
Issue with `rose sgc` (and potentially other cylc calls) whereby the calls are being run in the background by popen. If the calls fail, we currently don't know e.g. the `cylc gui` call from `rose sgc SOMETHING` fails but nothing gets reported back.

We should fork out processes once started successfully.

**Comment by oliver-sanders** [comment]
Closed by the removal of rose-cylc interaction at Cylc8.
