### ISSUE TITLE
rose edit: help for individual values

### ISSUE THREAD

**Issue by arjclark** [metomi/rose#669]
Follow up to #50 

It might be nice to be able to associate help with individual selectable values e.g.

`value-help[VAL] = My help string for VAL`

**Comment by matthewrmshin** [comment]
Is this issue addressed by `value-titles` (#668)?

**Comment by arjclark** [comment]
No, `value-titles` is how to render that value in the gui. This is for allowing help specifically for the value.

**Comment by arjclark** [comment]
Closing as surplus to requirements.
