### ISSUE TITLE
rose_ana: test battery

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#775]
Add tests for the built-in `rose_ana` application.

**Comment by scwhitehouse** [comment]
### Things to test

Including ones added by #1577

 - [X] OutputGrepper - Exact comparison fail - single numeric value
 - [X] OutputGrepper - Exact comparison success - single numeric value
 - [X] OutputGrepper - Exact comparison fail - single text value
 - [X] OutputGrepper - Exact comparison success - single text value
 - [X] OutputGrepper - Exact comparison fail - list of numeric values
 - [ ] OutputGrepper - Exact comparison success - list of numeric values
 - [X] OutputGrepper - Exact comparison fail - list of text values
 - [ ] OutputGrepper - Exact comparison success - list of text values
 - [X] OutputGrepper - Within comparison fail - percentage tolerance, single numeric value
 - [X] OutputGrepper - Within comparison success - percentage tolerance, single numeric value
 - [X] OutputGrepper - Within comparison fail - absolute tolerance, single numeric value
 - [X] OutputGrepper - Within comparison success - absolute tolerance, single numeric value
 - [X] OutputGrepper - Within comparison fail - percentage tolerance, list of numeric values
 - [X] OutputGrepper - Within comparison success - percentage tolerance, list of numeric values
 - [ ] OutputGrepper - Within comparison fail - absolute tolerance, list of numeric values
 - [ ] OutputGrepper - Within comparison success - absolute tolerance, list of numeric values
 - [ ] OutputGrepper - Preset keys test - fail
 - [ ] OutputGrepper - Preset keys test - success
 - [ ] OutputGrepper - External program test - fail, single command for both files
 - [ ] OutputGrepper - External program test - success, single command for both files
 - [ ] OutputGrepper - External program test - fail, separate commands for each file
 - [ ] OutputGrepper - External program test - success, separate commands for each file

**Comment by matthewrmshin** [comment]
@stevewardle Is this issue still relevant with your rewrite?

**Comment by stevewardle** [comment]
It's sort of relevant, thanks - although I was planning to go through the testing as part of the rewrite anyway (especially since the naming of everything has changed!)

**Comment by matthewrmshin** [comment]
#1996 has made the original list a bit redundant. Test battery for *rose_ana* should now be done business as usual.
