### ISSUE TITLE
rose edit: improved array table layout widget

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#879]
Following on from #651, it would be nice to have the ability to add and remove certain elements as a global operation across all variables in the widget. For example, it would be good to have a button to add an additional element to each variable value represented in the widget.

**Comment by arjclark** [comment]
@dpmatthews to understand requirement

**Comment by dpmatthews** [comment]
As well as add & remove, moving a column might also be useful. However, I don't think this is worth pursuing unless there is a clear demand.
