### ISSUE TITLE
rose suite-run: install files on hosts for specific tasks

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#963]
It is suggested that a push-install by `rose suite-run` to hosts of specific tasks may be required at some sites.

See also #7 and #190.

**Comment by matthewrmshin** [comment]
Are we still convinced that this is required?

**Comment by hjoliver** [comment]
I guess it's not *required* as such if you accept that it's OK to do multiple redundant installs to multiple  task hosts that actually share the same filesystem.  I haven't actually checked to see if this causes problems or is just redundant - are different task hosts handled sequentially or concurrently?  Even if it's just redundant, it might not be OK if truly massive files are involved.

**Comment by matthewrmshin** [comment]
The logic already has some intelligence to handle some of these cases:
* It does not do any installation if the target host shares the file system with the suite host. (On installation, a temporary file with a UUID name is created at the destination. It skips the host if the logic sees such a file.)
* It evaluates each unique task host string only once, so you only use the same (shell) string for a set of tasks, it will only install to a single host.
* Installation is done with concurrent `ssh` and `rsync` commands.

**Comment by dpmatthews** [comment]
We think the current logic is the best we can do for the moment. The whole suite installation approach will need to be looked at again as part of integrating it into cylc
